#!/usr/bin/env python3
"""
LAMMPS MD模拟自动化
使用机器学习势进行大尺度分子动力学
"""

import os
import json
import numpy as np
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Any
from dataclasses import dataclass
import logging
import subprocess
import tempfile

# ASE
from ase import Atoms
from ase.io import read, write
from ase.io.lammpsdata import write_lammps_data
from ase.io.lammpsrun import read_lammps_dump_text
from ase.md.velocitydistribution import MaxwellBoltzmannDistribution
from ase.md.verlet import VelocityVerlet
from ase.md.langevin import Langevin
from ase.md.nptberendsen import NPTBerendsen
from ase.md.nvtberendsen import NVTBerendsen
from ase.optimize import BFGS, FIRE, LBFGS
from ase.units import fs, kB, GPa
from ase.neighborlist import NeighborList
from ase.geometry.analysis import Analysis

# LAMMPS Python接口
# from lammps import lammps

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


@dataclass
class LAMMPSConfig:
    """LAMMPS模拟配置"""
    # 基本设置
    pair_style: str = "deepmd"  # deepmd, snap, pace, etc.
    potential_file: str = "graph.pb"
    
    # 模拟类型
    ensemble: str = "nvt"  # nve, nvt, npt
    temperature: float = 300.0  # K
    pressure: Optional[float] = None  # atm
    
    # 时间设置
    timestep: float = 1.0  # fs
    nsteps: int = 100000
    
    # 输出设置
    thermo_interval: int = 100
    dump_interval: int = 1000
    dump_file: str = "dump.lammpstrj"
    
    # 约束
    fix_com: bool = True  # 固定质心
    
    # 并行设置
    nprocs: int = 4
    
    # 路径
    lammps_cmd: str = "lmp"
    working_dir: str = "./lammps_run"


class LAMMPSInputGenerator:
    """LAMMPS输入文件生成器"""
    
    def __init__(self, config: LAMMPSConfig):
        self.config = config
        self.input_lines = []
        
    def generate_input(self, atoms: Atoms, output_file: str = "in.lammps") -> str:
        """生成完整LAMMPS输入文件"""
        
        # 初始化
        self._add_header()
        self._add_units()
        self._add_atom_style()
        self._add_boundary()
        self._add_read_data(atoms)
        
        # 势函数设置
        self._add_potential()
        
        # 邻居列表
        self._add_neighbor()
        
        # 约束
        self._add_constraints()
        
        # 输出设置
        self._add_output()
        
        # 温度初始化
        self._add_temperature_init()
        
        # 运行设置
        self._add_run()
        
        # 保存
        input_content = "\n".join(self.input_lines)
        
        Path(self.config.working_dir).mkdir(parents=True, exist_ok=True)
        input_path = Path(self.config.working_dir) / output_file
        
        with open(input_path, 'w') as f:
            f.write(input_content)
        
        logger.info(f"Generated LAMMPS input: {input_path}")
        
        # 写入结构数据
        self._write_data_file(atoms)
        
        return str(input_path)
    
    def _add_line(self, line: str):
        """添加一行输入"""
        self.input_lines.append(line)
    
    def _add_header(self):
        """添加文件头"""
        self._add_line("# LAMMPS input file generated by ASE interface")
        self._add_line("")
    
    def _add_units(self):
        """设置单位制"""
        self._add_line("units metal")
        self._add_line("dimension 3")
        self._add_line("")
    
    def _add_atom_style(self):
        """设置原子样式"""
        self._add_line("atom_style atomic")
        self._add_line("")
    
    def _add_boundary(self):
        """设置边界条件"""
        self._add_line("boundary p p p")
        self._add_line("")
    
    def _add_read_data(self, atoms: Atoms):
        """读取结构数据"""
        self._add_line("read_data structure.data")
        self._add_line("")
    
    def _write_data_file(self, atoms: Atoms):
        """写入LAMMPS数据文件"""
        data_file = Path(self.config.working_dir) / "structure.data"
        write_lammps_data(data_file, atoms, atom_style='atomic')
        logger.info(f"Wrote structure data: {data_file}")
    
    def _add_potential(self):
        """添加势函数设置"""
        pair_style = self.config.pair_style
        
        if pair_style == "deepmd":
            self._add_line(f"pair_style deepmd {self.config.potential_file}")
            self._add_line("pair_coeff * * ")
        elif pair_style == "snap":
            self._add_line(f"pair_style snap")
            self._add_line(f"pair_coeff * * {self.config.potential_file}")
        elif pair_style == "tersoff":
            self._add_line(f"pair_style tersoff")
            self._add_line(f"pair_coeff * * {self.config.potential_file}")
        elif pair_style == "eam/alloy":
            self._add_line(f"pair_style eam/alloy")
            self._add_line(f"pair_coeff * * {self.config.potential_file}")
        else:
            raise ValueError(f"Unsupported pair style: {pair_style}")
        
        self._add_line("")
    
    def _add_neighbor(self):
        """添加邻居列表设置"""
        self._add_line("neighbor 2.0 bin")
        self._add_line("neigh_modify every 10 delay 0 check yes")
        self._add_line("")
    
    def _add_constraints(self):
        """添加约束"""
        if self.config.fix_com:
            self._add_line("fix com_fix all momentum 100 linear 1 1 1")
        self._add_line("")
    
    def _add_output(self):
        """添加输出设置"""
        self._add_line(f"thermo {self.config.thermo_interval}")
        self._add_line("thermo_style custom step temp pe ke etotal press vol")
        self._add_line("")
        
        # Dump设置
        self._add_line(f"dump traj all custom {self.config.dump_interval} {self.config.dump_file} &")
        self._add_line("    id type x y z vx vy vz")
        self._add_line("")
    
    def _add_temperature_init(self):
        """添加温度初始化"""
        T = self.config.temperature
        
        self._add_line(f"velocity all create {T} 12345 dist gaussian")
        self._add_line("")
    
    def _add_run(self):
        """添加运行设置"""
        T = self.config.temperature
        P = self.config.pressure
        dt = self.config.timestep / 1000  # fs -> ps (metal units)
        nsteps = self.config.nsteps
        
        self._add_line(f"timestep {dt}")
        
        # 根据系综选择fix
        if self.config.ensemble == "nve":
            self._add_line("fix ensemble all nve")
            
        elif self.config.ensemble == "nvt":
            # Nose-Hoover thermostat
            self._add_line(f"fix ensemble all nvt temp {T} {T} 0.1")
            
        elif self.config.ensemble == "npt":
            if P is None:
                raise ValueError("Pressure must be specified for NPT ensemble")
            # Nose-Hoover thermostat + Parrinello-Rahman barostat
            self._add_line(f"fix ensemble all npt temp {T} {T} 0.1 iso {P} {P} 1.0")
        
        self._add_line("")
        
        # 运行
        self._add_line(f"run {nsteps}")
        
        # 取消fix
        self._add_line("unfix ensemble")
        if self.config.fix_com:
            self._add_line("unfix com_fix")


class LAMMPSSimulator:
    """LAMMPS模拟运行器"""
    
    def __init__(self, config: LAMMPSConfig):
        self.config = config
        self.input_generator = LAMMPSInputGenerator(config)
        
    def run_simulation(self, atoms: Atoms, input_file: Optional[str] = None) -> str:
        """
        运行LAMMPS模拟
        
        Returns:
            dump_file_path: 轨迹文件路径
        """
        # 生成输入文件
        if input_file is None:
            input_file = self.input_generator.generate_input(atoms)
        
        # 运行LAMMPS
        cmd = [
            "mpirun", "-np", str(self.config.nprocs),
            self.config.lammps_cmd,
            "-in", input_file,
            "-log", "log.lammps"
        ]
        
        logger.info(f"Running LAMMPS: {' '.join(cmd)}")
        
        try:
            result = subprocess.run(
                cmd,
                cwd=self.config.working_dir,
                capture_output=True,
                text=True,
                check=True
            )
            logger.info("LAMMPS simulation completed successfully")
        except subprocess.CalledProcessError as e:
            logger.error(f"LAMMPS simulation failed: {e}")
            logger.error(f"stdout: {e.stdout}")
            logger.error(f"stderr: {e.stderr}")
            raise
        
        dump_file = Path(self.config.working_dir) / self.config.dump_file
        return str(dump_file)
    
    def run_optimization(self, atoms: Atoms, fmax: float = 0.01) -> Atoms:
        """
        结构优化
        
        使用ASE的优化器
        """
        from ase.calculators.lammpsrun import LAMMPS
        
        calc = LAMMPS(
            command=f"{self.config.lammps_cmd} -in in.lammps",
            pair_style=self.config.pair_style,
            pair_coeff=[f"* * {self.config.potential_file}"],
            specorder=self._get_type_map(atoms),
            tmp_dir=self.config.working_dir
        )
        
        atoms.calc = calc
        
        optimizer = FIRE(atoms, logfile='opt.log')
        optimizer.run(fmax=fmax)
        
        return atoms
    
    def _get_type_map(self, atoms: Atoms) -> List[str]:
        """获取元素类型映射"""
        return list(set(atoms.get_chemical_symbols()))


class MDAnalyzer:
    """MD结果分析器"""
    
    def __init__(self, trajectory_file: str):
        self.trajectory_file = trajectory_file
        self.trajectory = None
        
    def read_trajectory(self) -> List[Atoms]:
        """读取LAMMPS轨迹"""
        # 使用ASE读取
        self.trajectory = read(self.trajectory_file, index=':', format='lammps-dump-text')
        logger.info(f"Loaded {len(self.trajectory)} frames")
        return self.trajectory
    
    def compute_msd(self, 
                   atom_type: Optional[str] = None,
                   timestep: float = 1.0) -> Tuple[np.ndarray, np.ndarray]:
        """
        计算均方位移 (MSD)
        
        Args:
            atom_type: 指定原子类型，None表示所有原子
            timestep: 时间步长 (fs)
            
        Returns:
            times: 时间数组
            msd: MSD数组
        """
        if self.trajectory is None:
            self.read_trajectory()
        
        # 获取初始位置
        initial_positions = self.trajectory[0].get_positions()
        
        # 计算MSD
        msd_values = []
        times = []
        
        for i, atoms in enumerate(self.trajectory):
            positions = atoms.get_positions()
            
            if atom_type:
                # 筛选特定原子类型
                symbols = atoms.get_chemical_symbols()
                indices = [j for j, s in enumerate(symbols) if s == atom_type]
                positions = positions[indices]
                initial = initial_positions[indices]
            else:
                initial = initial_positions
            
            # 计算MSD
            msd = np.mean(np.sum((positions - initial)**2, axis=1))
            msd_values.append(msd)
            times.append(i * timestep)
        
        return np.array(times), np.array(msd_values)
    
    def compute_diffusion_coefficient(self,
                                     atom_type: Optional[str] = None,
                                     start_frame: int = 100,
                                     end_frame: Optional[int] = None,
                                     timestep: float = 1.0) -> float:
        """
        从MSD计算扩散系数
        
        D = MSD / (6t)  (3D)
        
        Returns:
            diffusion_coefficient: cm^2/s
        """
        times, msd = self.compute_msd(atom_type, timestep)
        
        if end_frame is None:
            end_frame = len(times)
        
        # 线性拟合
        slope, intercept = np.polyfit(times[start_frame:end_frame], 
                                      msd[start_frame:end_frame], 1)
        
        # D = slope / 6 (3D) 单位: Å^2/fs
        D_ang2_fs = slope / 6
        
        # 转换为 cm^2/s
        D_cm2_s = D_ang2_fs * 1e-16 / 1e-15
        
        return D_cm2_s
    
    def compute_rdf(self,
                   rmax: float = 10.0,
                   nbins: int = 100,
                   element_pairs: Optional[List[Tuple[str, str]]] = None) -> Dict:
        """
        计算径向分布函数 (RDF)
        
        Args:
            rmax: 最大距离
            nbins: 分箱数
            element_pairs: 元素对列表，如 [("Li", "O"), ("O", "O")]
            
        Returns:
            rdf_data: 包含r和g(r)的字典
        """
        if self.trajectory is None:
            self.read_trajectory()
        
        # 使用ASE的Analysis
        dr = rmax / nbins
        rdf_data = {}
        
        for atoms in self.trajectory[::10]:  # 每10帧计算一次
            analysis = Analysis(atoms)
            
            if element_pairs is None:
                # 默认计算所有元素对
                symbols = list(set(atoms.get_chemical_symbols()))
                element_pairs = [(s1, s2) for s1 in symbols for s2 in symbols]
            
            for pair in element_pairs:
                g_r = analysis.get_rdf(rmax, nbins, elements=pair)
                
                if pair not in rdf_data:
                    rdf_data[pair] = []
                rdf_data[pair].append(g_r)
        
        # 平均
        results = {}
        r = np.linspace(0, rmax, nbins)
        
        for pair, g_r_list in rdf_data.items():
            g_r_avg = np.mean(g_r_list, axis=0)
            results[pair] = {'r': r, 'g_r': g_r_avg}
        
        return results
    
    def compute_temperature(self) -> np.ndarray:
        """从动能计算温度"""
        if self.trajectory is None:
            self.read_trajectory()
        
        temperatures = []
        
        for atoms in self.trajectory:
            # 计算温度: T = 2*KE/(3*N*kB)
            velocities = atoms.get_velocities()
            if velocities is not None:
                ke = 0.5 * np.sum(atoms.get_masses()[:, None] * velocities**2)
                n_atoms = len(atoms)
                T = 2 * ke / (3 * n_atoms * kB)
                temperatures.append(T)
        
        return np.array(temperatures)
    
    def compute_pressure(self) -> np.ndarray:
        """计算压强"""
        if self.trajectory is None:
            self.read_trajectory()
        
        # 从应力张量计算压强
        pressures = []
        
        for atoms in self.trajectory:
            stress = atoms.get_stress()
            if stress is not None:
                # 压强 = -迹/3
                pressure = -np.trace(stress[:3]) / 3
                pressures.append(pressure)
        
        return np.array(pressures)
    
    def compute_density(self) -> np.ndarray:
        """计算密度"""
        if self.trajectory is None:
            self.read_trajectory()
        
        densities = []
        
        for atoms in self.trajectory:
            mass = np.sum(atoms.get_masses())  # amu
            volume = atoms.get_volume()  # Å^3
            
            # 转换为 g/cm^3
            density = mass / volume * 1.66054
            densities.append(density)
        
        return np.array(densities)
    
    def compute_ionic_conductivity(self,
                                  charges: Dict[str, float],
                                  temperature: float,
                                  timestep: float = 1.0) -> float:
        """
        计算离子电导率 (Nernst-Einstein)
        
        σ = (n * q^2 * D) / (kB * T)
        
        Args:
            charges: 元素电荷字典，如 {"Li": 1.0, "O": -2.0}
            temperature: 温度 (K)
            timestep: 时间步长 (fs)
            
        Returns:
            conductivity: S/cm
        """
        conductivity = 0.0
        
        for element, charge in charges.items():
            # 计算扩散系数
            D = self.compute_diffusion_coefficient(
                atom_type=element,
                timestep=timestep
            )  # cm^2/s
            
            # 计算该元素的数密度
            n = self._compute_number_density(element)  # 1/cm^3
            
            # Nernst-Einstein方程
            # σ = n * q^2 * D / (kB * T)
            kB_si = 1.380649e-23  # J/K
            q_si = charge * 1.602e-19  # C
            
            sigma = n * q_si**2 * D * 1e-4 / (kB_si * temperature)  # S/cm
            
            conductivity += sigma
        
        return conductivity
    
    def _compute_number_density(self, element: str) -> float:
        """计算数密度"""
        if self.trajectory is None:
            self.read_trajectory()
        
        atoms = self.trajectory[0]
        n_element = atoms.get_chemical_symbols().count(element)
        volume = atoms.get_volume() * 1e-24  # Å^3 -> cm^3
        
        return n_element / volume
    
    def generate_report(self, output_file: str = "md_analysis_report.json"):
        """生成分析报告"""
        report = {
            'trajectory_file': self.trajectory_file,
            'n_frames': len(self.trajectory) if self.trajectory else 0,
            'properties': {}
        }
        
        if self.trajectory:
            # 温度
            temps = self.compute_temperature()
            report['properties']['temperature'] = {
                'mean': float(np.mean(temps)),
                'std': float(np.std(temps)),
                'min': float(np.min(temps)),
                'max': float(np.max(temps))
            }
            
            # 密度
            densities = self.compute_density()
            report['properties']['density'] = {
                'mean': float(np.mean(densities)),
                'std': float(np.std(densities)),
                'unit': 'g/cm^3'
            }
            
            # 扩散系数 (如果有速度信息)
            try:
                D = self.compute_diffusion_coefficient()
                report['properties']['diffusion_coefficient'] = {
                    'value': float(D),
                    'unit': 'cm^2/s'
                }
            except:
                pass
        
        with open(output_file, 'w') as f:
            json.dump(report, f, indent=2)
        
        logger.info(f"Generated analysis report: {output_file}")
        
        return report


class MDSimulationWorkflow:
    """完整MD模拟工作流"""
    
    def __init__(self, config: LAMMPSConfig):
        self.config = config
        self.simulator = LAMMPSSimulator(config)
        
    def equilibration_run(self, 
                         atoms: Atoms,
                         nvt_steps: int = 50000,
                         npt_steps: int = 50000) -> Atoms:
        """
        平衡化模拟
        
        1. NVT平衡
        2. NPT平衡 (如果需要)
        """
        logger.info("Starting equilibration...")
        
        # 阶段1: NVT
        logger.info(f"NVT equilibration: {nvt_steps} steps")
        self.config.ensemble = "nvt"
        self.config.nsteps = nvt_steps
        self.config.dump_interval = 1000
        
        dump_file = self.simulator.run_simulation(atoms)
        
        # 读取最后一帧作为NPT起点
        final_atoms = read(dump_file, index=-1, format='lammps-dump-text')
        
        # 阶段2: NPT (可选)
        if npt_steps > 0:
            logger.info(f"NPT equilibration: {npt_steps} steps")
            self.config.ensemble = "npt"
            self.config.nsteps = npt_steps
            
            dump_file = self.simulator.run_simulation(final_atoms)
            final_atoms = read(dump_file, index=-1, format='lammps-dump-text')
        
        return final_atoms
    
    def production_run(self,
                      atoms: Atoms,
                      nsteps: int = 1000000) -> str:
        """生产模拟"""
        logger.info(f"Starting production run: {nsteps} steps")
        
        self.config.nsteps = nsteps
        self.config.dump_interval = 100
        
        dump_file = self.simulator.run_simulation(atoms)
        
        return dump_file
    
    def full_workflow(self, initial_atoms: Atoms) -> Dict:
        """执行完整工作流"""
        # 平衡化
        equilibrated = self.equilibration_run(initial_atoms)
        
        # 生产模拟
        trajectory = self.production_run(equilibrated)
        
        # 分析
        analyzer = MDAnalyzer(trajectory)
        report = analyzer.generate_report()
        
        return {
            'trajectory': trajectory,
            'report': report
        }


def main():
    """示例用法"""
    
    # 配置
    config = LAMMPSConfig(
        pair_style="deepmd",
        potential_file="graph.pb",
        ensemble="nvt",
        temperature=300,
        timestep=1.0,
        nsteps=100000,
        nprocs=4
    )
    
    # 加载结构
    # atoms = read("POSCAR")
    
    # 运行模拟
    # simulator = LAMMPSSimulator(config)
    # dump_file = simulator.run_simulation(atoms)
    
    # 分析
    # analyzer = MDAnalyzer(dump_file)
    # D = analyzer.compute_diffusion_coefficient(atom_type="Li")
    # print(f"Li diffusion coefficient: {D:.2e} cm^2/s")
    
    print("LAMMPS MD Simulation template ready!")


if __name__ == "__main__":
    main()
