"""
VASPsol Advanced Module - 隐式溶剂模型与双电层计算

本模块实现VASPsol隐式溶剂模型的接口，支持：
- 线性/非线性Poisson-Boltzmann方程
- 双电层电容计算
- pH效应建模
- 溶剂化自由能计算

Author: DFT-LAMMPS Team
Date: 2025
"""

import os
import re
import numpy as np
from typing import Dict, List, Optional, Tuple, Union, Callable
from dataclasses import dataclass, field
from pathlib import Path
import json
import subprocess
import warnings
from enum import Enum


class SolvationModel(Enum):
    """VASPsol溶剂化模型类型"""
    LINEAR_PB = "linear_pb"           # 线性Poisson-Boltzmann
    NONLINEAR_PB = "nonlinear_pb"     # 非线性Poisson-Boltzmann
    LPB = "lpb"                       # 局域极化模型
    GENERALIZED_BORN = "gb"           # 广义Born模型


@dataclass
class VASPsolParameters:
    """
    VASPsol隐式溶剂模型参数
    
    Attributes:
        tau: 腔体形状参数（建议值: 0.525）
        lambda_d: Debye屏蔽长度（Angstrom）
        c_kappa: 离子浓度（M）
        eb_k: 溶剂介电常数（水: 78.4）
        nc_k: 腔体介电常数（真空: 1.0）
        sigma_k: 腔体表面张力（dyn/cm）
        lacparam: 腔体参数a（Angstrom^-1）
        lbcparam: 腔体参数b（无量纲）
        lrho_min: 最小电荷密度截断
        esm_bc: ESM边界条件类型
    """
    # 基本参数
    tau: float = 0.525                # 腔体形状参数
    eb_k: float = 78.4                # 溶剂介电常数（水）
    nc_k: float = 1.0                 # 腔体介电常数
    
    # 双电层参数
    lambda_d: float = 3.0             # Debye长度（Angstrom）
    c_kappa: float = 0.1              # 离子浓度（M）
    temperature: float = 298.15       # 温度（K）
    
    # 表面张力参数
    sigma_k: float = 50.0             # 表面张力（dyn/cm）
    
    # 腔体参数
    lacparam: float = 0.00625         # 参数a
    lbcparam: float = 0.0             # 参数b
    lrho_min: float = 0.0001          # 最小电荷密度
    
    # ESM参数
    esm_bc: str = "VAC"               # 边界条件: VAC/PBC/BC1/BC2
    esm_w: float = 10.0               # ESM真空区域宽度
    
    # pH相关参数
    ph: float = 7.0                   # pH值
    ph_ref: float = 7.0               # 参考pH值
    zpe_solvation: float = 0.0        # 零点能校正
    
    # 计算参数
    lsol: bool = True                 # 开启溶剂化
    lwave: bool = True                # 输出波函数
    lcharg: bool = True               # 输出电荷密度
    
    def to_incar_dict(self) -> Dict[str, Union[str, float, bool]]:
        """转换为INCAR参数字典"""
        params = {
            "LSOL": ".TRUE." if self.lsol else ".FALSE.",
            "EB_K": self.eb_k,
            "NC_K": self.nc_k,
            "TAU": self.tau,
            "LAMBDA_D": self.lambda_d,
            "C_KAPPA": self.c_kappa,
            "SIGMA_K": self.sigma_k,
            "LACPARAM": self.lacparam,
            "LBCPARAM": self.lbcparam,
            "LRHO_MIN": self.lrho_min,
            "ESM_BC": self.esm_bc,
            "ESM_W": self.esm_w,
            "LWAVE": ".TRUE." if self.lwave else ".FALSE.",
            "LCHARG": ".TRUE." if self.lcharg else ".FALSE.",
        }
        return params


@dataclass
class ElectrolyteParameters:
    """电解质溶液参数"""
    dielectric_constant: float = 78.4
    viscosity: float = 0.89
    density: float = 1.0
    cations: Dict[str, float] = field(default_factory=dict)
    anions: Dict[str, float] = field(default_factory=dict)
    ph: float = 7.0
    temperature: float = 298.15
    
    def calculate_debye_length(self) -> float:
        """计算Debye屏蔽长度（Angstrom）"""
        I = 0.5 * (sum(self.cations.values()) + sum(self.anions.values()))
        eps_0 = 8.854e-12
        k_B = 1.381e-23
        e = 1.602e-19
        N_A = 6.022e23
        
        lambda_d_m = np.sqrt(
            eps_0 * self.dielectric_constant * k_B * self.temperature /
            (2 * N_A * e**2 * I * 1000)
        )
        return lambda_d_m * 1e10


class VASPsolCalculator:
    """VASPsol隐式溶剂计算器"""
    
    def __init__(
        self,
        sol_params: VASPsolParameters,
        vasp_cmd: str = "vasp_std",
        mpi_cmd: str = "mpirun -np 4",
        work_dir: str = "./vaspsol_calc"
    ):
        self.sol_params = sol_params
        self.vasp_cmd = vasp_cmd
        self.mpi_cmd = mpi_cmd
        self.work_dir = Path(work_dir)
        self.work_dir.mkdir(parents=True, exist_ok=True)
        self.results: Dict[str, float] = {}
        self.vacuum_energy: Optional[float] = None
        self.solvated_energy: Optional[float] = None
        
    def write_incar(self, base_incar: Union[str, Path, Dict], output_path: Path):
        """写入包含VASPsol参数的INCAR文件"""
        if isinstance(base_incar, (str, Path)):
            base_params = self._parse_incar(base_incar)
        else:
            base_params = base_incar.copy()
        
        sol_dict = self.sol_params.to_incar_dict()
        base_params.update(sol_dict)
        
        with open(output_path, 'w') as f:
            f.write("# VASPsol Implicit Solvation Calculation\n")
            f.write("# Generated by DFT-LAMMPS VASPsol Module\n\n")
            for key, value in base_params.items():
                f.write(f"{key:15s} = {value}\n")
    
    def _parse_incar(self, incar_path: Union[str, Path]) -> Dict:
        """解析INCAR文件为字典"""
        params = {}
        with open(incar_path, 'r') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                if '=' in line:
                    key, value = line.split('=', 1)
                    params[key.strip()] = value.strip()
        return params


class DoubleLayerCalculator:
    """双电层计算器"""
    
    def __init__(self, electrolyte: ElectrolyteParameters):
        self.electrolyte = electrolyte
        self.capacitance_data: List[Dict] = []
        
    def calculate_differential_capacitance(
        self, charges: np.ndarray, potentials: np.ndarray, method: str = "spline"
    ) -> np.ndarray:
        """计算微分电容 C = dσ/dφ"""
        if len(charges) != len(potentials):
            raise ValueError("charges和potentials长度必须相同")
        
        sort_idx = np.argsort(potentials)
        phi_sorted = potentials[sort_idx]
        sigma_sorted = charges[sort_idx]
        
        if method == "spline":
            # 简单差分近似
            capacitance = np.gradient(sigma_sorted, phi_sorted)
        else:
            capacitance = np.gradient(sigma_sorted, phi_sorted)
        
        self.capacitance_data = [
            {"potential": phi, "charge": sig, "capacitance": cap}
            for phi, sig, cap in zip(phi_sorted, sigma_sorted, capacitance)
        ]
        
        return capacitance
    
    def calculate_helmholtz_capacitance(
        self, dielectric_constant: Optional[float] = None, thickness: float = 3.0
    ) -> float:
        """计算亥姆霍兹层电容 C_H = ε₀εᵣ/d"""
        eps = dielectric_constant or self.electrolyte.dielectric_constant
        eps_0 = 8.854e-12  # F/m
        c_h = (eps_0 * eps) / (thickness * 1e-10)  # F/m²
        c_h = c_h * 1e6 / 1e4  # μF/cm²
        return c_h
    
    def calculate_diffuse_layer_capacitance(
        self, potential: float, ionic_strength: Optional[float] = None
    ) -> float:
        """计算扩散层电容（Gouy-Chapman模型）"""
        I = ionic_strength or 0.1
        lambda_d = self.electrolyte.calculate_debye_length() * 1e-10
        eps_0 = 8.854e-12
        eps_r = self.electrolyte.dielectric_constant
        F = 96485
        R = 8.314
        T = self.electrolyte.temperature
        
        x = F * potential / (2 * R * T)
        cosh_term = np.cosh(x)
        c_gc = (eps_0 * eps_r / lambda_d) * cosh_term
        c_gc = c_gc * 1e6 / 1e4
        return c_gc


class pHCalculator:
    """pH效应计算器"""
    
    def __init__(self, temperature: float = 298.15):
        self.temperature = temperature
        self.kT = 8.617e-5 * temperature
        
    def calculate_ph_correction(self, ph: float, ne: int = 1, nh: int = 1, reference_ph: float = 7.0) -> float:
        """计算pH依赖的能量校正"""
        return -self.kT * nh * np.log(10) * (ph - reference_ph)


# 使用示例
def example_basic_calculation():
    """基本溶剂化计算示例"""
    electrolyte = ElectrolyteParameters(
        dielectric_constant=78.4, ph=7.0,
        cations={"Na+": 0.1}, anions={"Cl-": 0.1}
    )
    lambda_d = electrolyte.calculate_debye_length()
    print(f"Debye长度: {lambda_d:.2f} Angstrom")
    
    sol_params = VASPsolParameters(tau=0.525, eb_k=78.4, lambda_d=lambda_d)
    calc = VASPsolCalculator(sol_params, work_dir="./example_vaspsol")
    print(f"VASPsol参数已创建: tau={sol_params.tau}")


def example_double_layer():
    """双电层计算示例"""
    electrolyte = ElectrolyteParameters(cations={"Na+": 0.1}, anions={"Cl-": 0.1})
    dlc = DoubleLayerCalculator(electrolyte)
    
    charges = np.array([-20, -10, 0, 10, 20])
    potentials = np.array([-0.5, -0.2, 0.0, 0.2, 0.5])
    c_diff = dlc.calculate_differential_capacitance(charges, potentials)
    print(f"微分电容: {c_diff}")


def example_pH_effects():
    """pH效应计算示例"""
    ph_calc = pHCalculator(temperature=298.15)
    for ph in [0, 7, 14]:
        correction = ph_calc.calculate_ph_correction(ph, nh=1, reference_ph=7.0)
        print(f"pH {ph}: 能量校正 = {correction:.4f} eV")


class SolvationAnalysis:
    """溶剂化分析工具"""
    
    def __init__(self):
        self.solvent_contributions = {}
        
    def analyze_cavity_contribution(self, cavitation_energy: float, surface_area: float) -> Dict:
        """分析腔体贡献"""
        gamma_eff = cavitation_energy / surface_area if surface_area > 0 else 0
        return {
            "cavitation_energy": cavitation_energy,
            "surface_area": surface_area,
            "effective_surface_tension": gamma_eff,
        }
    
    def analyze_dielectric_contribution(self, polarization_energy: float, 
                                       dipole_moment: float) -> Dict:
        """分析介电贡献"""
        return {
            "polarization_energy": polarization_energy,
            "dipole_moment": dipole_moment,
            "interaction_strength": abs(polarization_energy) / (dipole_moment + 1e-10),
        }
    
    def calculate_solvent_reorganization_energy(
        self, 
        oxidized_state_energy: float,
        reduced_state_energy: float,
        vacuum_energy_diff: float
    ) -> float:
        """计算溶剂重组能（Marcus理论）"""
        # λ = (E_ox - E_red) - ΔE_vacuum
        return (oxidized_state_energy - reduced_state_energy) - vacuum_energy_diff


class VASPsolPostProcessor:
    """VASPsol后处理器"""
    
    def __init__(self, output_dir: str = "./vaspsol_output"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)
        
    def extract_solvation_terms(self, outcar_path: Union[str, Path]) -> Dict:
        """从OUTCAR提取溶剂化项"""
        # 简化实现
        return {
            "cavitation_energy": 0.0,
            "dielectric_energy": 0.0,
            "total_solvation": 0.0,
        }
    
    def calculate_binding_energy_solvation(
        self,
        complex_energy_solv: float,
        substrate_energy_solv: float,
        adsorbate_energy_solv: float,
        complex_energy_vac: float,
        substrate_energy_vac: float,
        adsorbate_energy_vac: float
    ) -> Dict:
        """计算溶剂化条件下的结合能"""
        # 真空结合能
        binding_vac = complex_energy_vac - substrate_energy_vac - adsorbate_energy_vac
        
        # 溶剂化结合能
        binding_solv = complex_energy_solv - substrate_energy_solv - adsorbate_energy_solv
        
        # 溶剂化效应
        solvation_effect = binding_solv - binding_vac
        
        return {
            "binding_energy_vacuum": binding_vac,
            "binding_energy_solvation": binding_solv,
            "solvation_effect": solvation_effect,
        }


class ESMInterface:
    """ESM（Effective Screening Medium）接口"""
    
    def __init__(self, boundary_condition: str = "VAC", vacuum_width: float = 10.0):
        """
        初始化ESM接口
        
        Args:
            boundary_condition: 边界条件 (VAC/PBC/BC1/BC2)
            vacuum_width: 真空区域宽度 (Angstrom)
        """
        self.boundary_condition = boundary_condition
        self.vacuum_width = vacuum_width
        
    def get_incar_params(self) -> Dict[str, Union[str, float]]:
        """获取ESM的INCAR参数"""
        return {
            "ESM_BC": self.boundary_condition,
            "ESM_W": self.vacuum_width,
        }
    
    def calculate_image_charge_correction(
        self,
        charge: float,
        distance_to_interface: float,
        dielectric_constant: float = 78.4
    ) -> float:
        """计算镜像电荷校正"""
        # 简化模型: E_correction = -Q²/(4εd)
        eps_0 = 8.854e-12
        e = 1.602e-19
        
        correction_joule = -(charge * e)**2 / (4 * dielectric_constant * eps_0 * distance_to_interface * 1e-10)
        correction_ev = correction_joule / e
        
        return correction_ev


# 扩展的使用示例
def example_advanced_capacitance():
    """高级电容计算示例"""
    print("\n4. 高级电容计算示例")
    print("-" * 40)
    
    electrolyte = ElectrolyteParameters(
        dielectric_constant=78.4,
        cations={"Na+": 0.1},
        anions={"Cl-": 0.1}
    )
    
    dlc = DoubleLayerCalculator(electrolyte)
    
    # 亥姆霍兹电容
    c_h = dlc.calculate_helmholtz_capacitance(thickness=3.0)
    print(f"亥姆霍兹电容: {c_h:.2f} μF/cm²")
    
    # 扩散层电容
    c_gc = dlc.calculate_diffuse_layer_capacitance(potential=0.5)
    print(f"扩散层电容 (@0.5V): {c_gc:.2f} μF/cm²")
    
    # 总电容
    c_total = 1.0 / (1.0/c_h + 1.0/c_gc)
    print(f"总电容: {c_total:.2f} μF/cm²")


def example_solvation_analysis():
    """溶剂化分析示例"""
    print("\n5. 溶剂化分析示例")
    print("-" * 40)
    
    analyzer = SolvationAnalysis()
    
    # 腔体分析
    cavity_result = analyzer.analyze_cavity_contribution(
        cavitation_energy=0.5,  # eV
        surface_area=50.0  # Å²
    )
    print(f"腔体分析:")
    print(f"  有效表面张力: {cavity_result['effective_surface_tension']*1e3:.2f} meV/Å²")
    
    # 介电分析
    dielectric_result = analyzer.analyze_dielectric_contribution(
        polarization_energy=-2.5,
        dipole_moment=2.0
    )
    print(f"介电分析:")
    print(f"  极化能: {dielectric_result['polarization_energy']:.2f} eV")
    
    # 重组能
    reorg_energy = analyzer.calculate_solvent_reorganization_energy(
        oxidized_state_energy=-100.0,
        reduced_state_energy=-105.0,
        vacuum_energy_diff=5.2
    )
    print(f"溶剂重组能: {reorg_energy:.2f} eV")


def example_esm_interface():
    """ESM接口示例"""
    print("\n6. ESM接口示例")
    print("-" * 40)
    
    esm = ESMInterface(boundary_condition="VAC", vacuum_width=15.0)
    
    params = esm.get_incar_params()
    print(f"ESM参数:")
    for key, value in params.items():
        print(f"  {key}: {value}")
    
    # 镜像电荷校正
    correction = esm.calculate_image_charge_correction(
        charge=1.0,
        distance_to_interface=5.0
    )
    print(f"镜像电荷校正: {correction:.4f} eV")


class ZPECalculator:
    """零点能计算器 - 溶剂化效应"""
    
    def __init__(self, temperature: float = 298.15):
        self.temperature = temperature
        self.kT = 8.617e-5 * temperature
        
    def calculate_zpe_correction(
        self, 
        frequencies_vacuum: np.ndarray,
        frequencies_solution: np.ndarray
    ) -> float:
        """
        计算溶剂化引起的ZPE校正
        
        Args:
            frequencies_vacuum: 真空中的振动频率 (cm^-1)
            frequencies_solution: 溶液中的振动频率 (cm^-1)
            
        Returns:
            ZPE校正能量 (eV)
        """
        # ZPE = 0.5 * Σ hν
        h = 4.136e-15  # eV·s
        c = 3e10  # cm/s
        
        zpe_vac = 0.5 * np.sum(h * c * frequencies_vacuum)
        zpe_sol = 0.5 * np.sum(h * c * frequencies_solution)
        
        return zpe_sol - zpe_vac
    
    def calculate_entropy_contribution(
        self,
        frequencies: np.ndarray,
        symmetry_number: int = 1
    ) -> float:
        """计算振动熵贡献"""
        # 简化计算
        h = 4.136e-15
        c = 3e10
        k_B = 8.617e-5
        
        entropy = 0.0
        for nu in frequencies:
            if nu > 0:
                x = h * c * nu / (k_B * self.temperature)
                entropy += k_B * (x / (np.exp(x) - 1) - np.log(1 - np.exp(-x)))
        
        return entropy


class ImplicitSolventDatabase:
    """隐式溶剂参数数据库"""
    
    def __init__(self):
        self.solvents = {
            "water": {
                "epsilon": 78.4,
                "n": 1.33,
                "surface_tension": 72.0,
                "temperature_range": (273, 373),
            },
            "acetonitrile": {
                "epsilon": 37.5,
                "n": 1.34,
                "surface_tension": 28.7,
                "temperature_range": (250, 350),
            },
            "methanol": {
                "epsilon": 32.7,
                "n": 1.33,
                "surface_tension": 22.1,
                "temperature_range": (200, 350),
            },
            "dmso": {
                "epsilon": 47.2,
                "n": 1.48,
                "surface_tension": 43.0,
                "temperature_range": (250, 400),
            },
            "dcm": {
                "epsilon": 9.1,
                "n": 1.42,
                "surface_tension": 26.5,
                "temperature_range": (200, 350),
            },
            "thf": {
                "epsilon": 7.6,
                "n": 1.41,
                "surface_tension": 26.4,
                "temperature_range": (200, 350),
            },
        }
    
    def get_solvent_params(self, name: str) -> Dict:
        """获取溶剂参数"""
        return self.solvents.get(name.lower(), {})
    
    def list_available_solvents(self) -> List[str]:
        """列出可用溶剂"""
        return list(self.solvents.keys())
    
    def estimate_permittivity(self, temperature: float, solvent: str = "water") -> float:
        """估算温度依赖的介电常数"""
        params = self.get_solvent_params(solvent)
        if not params:
            return 78.4
        
        # 简化模型: ε ∝ 1/T
        eps_ref = params["epsilon"]
        T_ref = 298.15
        
        eps = eps_ref * T_ref / temperature
        return eps


class ReactionFieldCalculator:
    """反应场计算器 - Onsager模型"""
    
    def __init__(self, dielectric_constant: float = 78.4):
        self.epsilon = dielectric_constant
        
    def calculate_reaction_field_factor(self) -> float:
        """计算反应场因子 f = (2ε-2)/(2ε+1)"""
        return (2 * self.epsilon - 2) / (2 * self.epsilon + 1)
    
    def calculate_solvation_energy_onssager(
        self,
        dipole_moment: float,
        cavity_radius: float
    ) -> float:
        """
        使用Onsager模型计算溶剂化能
        
        ΔG = -f μ² / (4πε₀ a³)
        
        Args:
            dipole_moment: 偶极矩 (Debye)
            cavity_radius: 腔体半径 (Angstrom)
            
        Returns:
            溶剂化能 (eV)
        """
        f = self.calculate_reaction_field_factor()
        
        # 单位转换
        mu_si = dipole_moment * 3.336e-30  # C·m
        a_si = cavity_radius * 1e-10  # m
        eps_0 = 8.854e-12  # F/m
        
        # 能量 (J)
        E_joule = -f * mu_si**2 / (4 * np.pi * eps_0 * a_si**3)
        
        # 转换为eV
        E_ev = E_joule / 1.602e-19
        
        return E_ev


# 更多使用示例
def example_zpe_calculation():
    """ZPE计算示例"""
    print("\n7. ZPE计算示例")
    print("-" * 40)
    
    zpe_calc = ZPECalculator(temperature=298.15)
    
    # 模拟频率数据 (cm^-1)
    freq_vac = np.array([500, 1000, 1500, 3000])
    freq_sol = np.array([480, 980, 1460, 2980])  # 红移
    
    zpe_corr = zpe_calc.calculate_zpe_correction(freq_vac, freq_sol)
    print(f"ZPE校正: {zpe_corr*1e3:.2f} meV")
    
    # 熵贡献
    entropy = zpe_calc.calculate_entropy_contribution(freq_sol)
    print(f"振动熵: {entropy*1e3:.2f} meV/K")


def example_solvent_database():
    """溶剂数据库示例"""
    print("\n8. 溶剂数据库示例")
    print("-" * 40)
    
    db = ImplicitSolventDatabase()
    
    print("可用溶剂:")
    for solvent in db.list_available_solvents():
        params = db.get_solvent_params(solvent)
        print(f"  {solvent:15s} ε = {params['epsilon']:.1f}")
    
    # 温度依赖
    print("\n水的介电常数温度依赖:")
    for T in [273, 298, 323, 373]:
        eps = db.estimate_permittivity(T, "water")
        print(f"  T = {T} K: ε = {eps:.1f}")


def example_reaction_field():
    """反应场示例"""
    print("\n9. 反应场计算示例")
    print("-" * 40)
    
    rf_calc = ReactionFieldCalculator(dielectric_constant=78.4)
    
    f_factor = rf_calc.calculate_reaction_field_factor()
    print(f"反应场因子: {f_factor:.4f}")
    
    # Onsager溶剂化能
    solv_energy = rf_calc.calculate_solvation_energy_onssager(
        dipole_moment=2.0,  # Debye
        cavity_radius=3.0   # Angstrom
    )
    print(f"Onsager溶剂化能: {solv_energy:.3f} eV")


if __name__ == "__main__":
    print("=" * 60)
    print("VASPsol Advanced Module - 使用示例")
    print("=" * 60)
    
    print("\n1. 基本溶剂化计算示例")
    print("-" * 40)
    example_basic_calculation()
    
    print("\n2. 双电层计算示例")
    print("-" * 40)
    example_double_layer()
    
    print("\n3. pH效应计算示例")
    print("-" * 40)
    example_pH_effects()
    
    print("\n4. 高级电容计算示例")
    print("-" * 40)
    example_advanced_capacitance()
    
    print("\n5. 溶剂化分析示例")
    print("-" * 40)
    example_solvation_analysis()
    
    print("\n6. ESM接口示例")
    print("-" * 40)
    example_esm_interface()
    
    print("\n7. ZPE计算示例")
    print("-" * 40)
    example_zpe_calculation()
    
    print("\n8. 溶剂数据库示例")
    print("-" * 40)
    example_solvent_database()
    
    print("\n9. 反应场计算示例")
    print("-" * 40)
    example_reaction_field()
    
    print("\n" + "=" * 60)
    print("所有示例完成!")
    print("=" * 60)