"""
VQE Interface Module - Variational Quantum Eigensolver
变分量子本征求解器接口模块

本模块实现了VQE算法用于分子基态能量计算，包括：
- 标准VQE实现
- UCCSD ansatz
- 自适应VQE (ADAPT-VQE)
- PySCF接口

作者: Quantum Computing Team
版本: 1.0.0
"""

import numpy as np
from typing import List, Tuple, Dict, Optional, Callable, Union, Any
from dataclasses import dataclass, field
from enum import Enum
import warnings
from abc import ABC, abstractmethod

# 尝试导入量子计算库
try:
    from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
    from qiskit.circuit import Parameter
    from qiskit.primitives import Estimator
    from qiskit_algorithms import VQE as QiskitVQE
    from qiskit_algorithms.optimizers import COBYLA, L_BFGS_B, SLSQP
    from qiskit_nature.second_q.drivers import PySCFDriver
    from qiskit_nature.second_q.mappers import JordanWignerMapper, ParityMapper
    from qiskit_nature.second_q.circuit.library import UCCSD, HartreeFock
    from qiskit_nature.second_q.algorithms import GroundStateEigensolver
    from qiskit_nature.second_q.problems import ElectronicStructureProblem
    QISKIT_AVAILABLE = True
except ImportError:
    QISKIT_AVAILABLE = False
    warnings.warn("Qiskit not available. VQE functionality will be limited.")

try:
    import pennylane as qml
    from pennylane import qchem
    PENNYLANE_AVAILABLE = True
except ImportError:
    PENNYLANE_AVAILABLE = False
    warnings.warn("PennyLane not available. Some VQE features disabled.")

try:
    from pyscf import gto, scf, mcscf, fci, ao2mo
    from pyscf.lo import orth
    PYSCF_AVAILABLE = True
except ImportError:
    PYSCF_AVAILABLE = False
    warnings.warn("PySCF not available. Classical interface limited.")


class AnsatzType(Enum):
    """Ansatz类型枚举"""
    UCCSD = "uccsd"           # Unitary Coupled Cluster with Singles and Doubles
    UCCGSD = "uccgsd"         # UCC with Generalized Singles and Doubles
    ADAPT = "adapt"           # Adaptive ansatz
    HEA = "hea"               # Hardware Efficient Ansatz
    QAOA = "qaoa"             # QAOA ansatz
    CUSTOM = "custom"         # 自定义ansatz


class MapperType(Enum):
    """费米子-量子比特映射类型"""
    JORDAN_WIGNER = "jordan_wigner"
    PARITY = "parity"
    BRAVYI_KITAEV = "bravyi_kitaev"


@dataclass
class MolecularData:
    """分子数据结构"""
    atoms: List[Tuple[str, Tuple[float, float, float]]]
    basis: str = "sto-3g"
    charge: int = 0
    spin: int = 0
    unit: str = "Angstrom"
    
    # 计算结果
    n_electrons: Optional[int] = None
    n_orbitals: Optional[int] = None
    nuclear_repulsion: Optional[float] = None
    hf_energy: Optional[float] = None
    fci_energy: Optional[float] = None
    
    def __post_init__(self):
        if self.n_electrons is None and PYSCF_AVAILABLE:
            self._calculate_basic_info()
    
    def _calculate_basic_info(self):
        """计算基本分子信息"""
        mol = self.to_pyscf_molecule()
        self.n_electrons = mol.nelectron
        self.n_orbitals = mol.nao
        self.nuclear_repulsion = mol.energy_nuc()
        
        # HF计算
        mf = scf.RHF(mol)
        mf.kernel()
        self.hf_energy = mf.e_tot
    
    def to_pyscf_molecule(self):
        """转换为PySCF分子对象"""
        if not PYSCF_AVAILABLE:
            raise ImportError("PySCF is required")
        
        atom_str = ""
        for symbol, coords in self.atoms:
            atom_str += f"{symbol} {coords[0]} {coords[1]} {coords[2]};"
        
        mol = gto.M(
            atom=atom_str.rstrip(";"),
            basis=self.basis,
            charge=self.charge,
            spin=self.spin,
            unit=self.unit
        )
        return mol
    
    def to_xyz(self) -> str:
        """转换为XYZ格式字符串"""
        xyz = f"{len(self.atoms)}\n"
        xyz += f"Generated by DFT-LAMMPS Quantum Module\n"
        for symbol, coords in self.atoms:
            xyz += f"{symbol} {coords[0]:.6f} {coords[1]:.6f} {coords[2]:.6f}\n"
        return xyz


@dataclass
class VQEConfig:
    """VQE配置参数"""
    # 算法参数
    ansatz_type: AnsatzType = AnsatzType.UCCSD
    mapper_type: MapperType = MapperType.JORDAN_WIGNER
    optimizer: str = "COBYLA"
    max_iterations: int = 1000
    convergence_tolerance: float = 1e-6
    
    # Ansatz参数
    excitation_level: str = "sd"  # s, d, sd, sdg
    n_layers: int = 1  # 用于HEA等分层ansatz
    entanglement: str = "linear"  # 纠缠模式
    
    # 自适应VQE参数
    adapt_threshold: float = 1e-3
    adapt_max_operators: int = 100
    
    # 量子比特约简
    use_z2_symmetry: bool = True
    use_two_qubit_reduction: bool = True
    freeze_core: bool = True
    
    # 初始态
    use_hf_initial: bool = True
    
    # 经典模拟器
    backend: str = "statevector"  # statevector, qasm, density_matrix
    shots: Optional[int] = None  # None表示精确模拟
    
    # 误差缓解
    use_error_mitigation: bool = False
    error_mitigation_method: str = "zero_noise_extrapolation"


class VQEResult:
    """VQE计算结果"""
    
    def __init__(self):
        self.success: bool = False
        self.ground_state_energy: Optional[float] = None
        self.optimal_parameters: Optional[np.ndarray] = None
        self.energy_history: List[float] = []
        self.n_iterations: int = 0
        self.n_function_evals: int = 0
        self.ansatz_circuit: Optional[Any] = None
        self.n_qubits: Optional[int] = None
        self.n_cnots: Optional[int] = None
        self.circuit_depth: Optional[int] = None
        self.metadata: Dict[str, Any] = {}
        
        # 化学相关
        self.dipole_moment: Optional[Tuple[float, float, float]] = None
        self.total_angular_momentum: Optional[float] = None
        self.particle_number: Optional[float] = None
        self.magnetization: Optional[float] = None
        
    def to_dict(self) -> Dict[str, Any]:
        """转换为字典"""
        return {
            "success": self.success,
            "ground_state_energy": self.ground_state_energy,
            "energy_unit": "Hartree",
            "n_iterations": self.n_iterations,
            "n_qubits": self.n_qubits,
            "n_cnots": self.n_cnots,
            "circuit_depth": self.circuit_depth,
            "metadata": self.metadata
        }


class AnsatzBuilder(ABC):
    """Ansatz构建器基类"""
    
    @abstractmethod
    def build(self, n_qubits: int, n_electrons: int, params: np.ndarray) -> Any:
        """构建ansatz电路"""
        pass
    
    @abstractmethod
    def get_num_parameters(self, n_qubits: int, n_electrons: int) -> int:
        """获取参数数量"""
        pass


class UCCSDAnsatz(AnsatzBuilder):
    """UCCSD Ansatz构建器"""
    
    def __init__(self, config: VQEConfig):
        self.config = config
    
    def build(self, n_qubits: int, n_electrons: int, params: np.ndarray) -> Any:
        """构建UCCSD ansatz"""
        if not QISKIT_AVAILABLE:
            raise ImportError("Qiskit Nature required for UCCSD ansatz")
        
        # 创建费米子激发算符
        mapper = self._get_mapper()
        
        # Hartree-Fock初始态
        init_state = HartreeFock(
            num_spatial_orbitals=n_qubits // 2,
            num_particles=(n_electrons // 2, n_electrons // 2),
            qubit_mapper=mapper
        )
        
        # UCCSD ansatz
        ansatz = UCCSD(
            num_spatial_orbitals=n_qubits // 2,
            num_particles=(n_electrons // 2, n_electrons // 2),
            qubit_mapper=mapper,
            initial_state=init_state
        )
        
        return ansatz
    
    def get_num_parameters(self, n_qubits: int, n_electrons: int) -> int:
        """计算UCCSD参数数量"""
        n_occ = n_electrons // 2
        n_vir = (n_qubits // 2) - n_occ
        
        # 单激发 + 双激发
        n_singles = n_occ * n_vir
        n_doubles = (n_occ * (n_occ - 1) // 2) * (n_vir * (n_vir - 1) // 2)
        
        return n_singles + n_doubles
    
    def _get_mapper(self):
        """获取费米子-量子比特映射器"""
        if self.config.mapper_type == MapperType.JORDAN_WIGNER:
            return JordanWignerMapper()
        elif self.config.mapper_type == MapperType.PARITY:
            return ParityMapper(num_particles=(0, 0))
        else:
            return JordanWignerMapper()


class HardwareEfficientAnsatz(AnsatzBuilder):
    """硬件高效Ansatz (HEA)"""
    
    def __init__(self, config: VQEConfig):
        self.config = config
    
    def build(self, n_qubits: int, n_electrons: int, params: np.ndarray) -> Any:
        """构建硬件高效ansatz"""
        if not QISKIT_AVAILABLE:
            raise ImportError("Qiskit required")
        
        from qiskit.circuit.library import EfficientSU2
        
        ansatz = EfficientSU2(
            n_qubits,
            reps=self.config.n_layers,
            entanglement=self.config.entanglement,
            skip_unentangled_qubits=False
        )
        
        # 设置初始参数
        if params is not None:
            ansatz.assign_parameters(params, inplace=True)
        
        return ansatz
    
    def get_num_parameters(self, n_qubits: int, n_electrons: int) -> int:
        """计算HEA参数数量"""
        # 每个旋转门2个参数 (Ry, Rz) + 纠缠层
        params_per_layer = 2 * n_qubits
        if self.config.entanglement != "none":
            params_per_layer += n_qubits  # CNOT不需要参数，但可能有额外的旋转
        return params_per_layer * self.config.n_layers


class ADAPTVQE:
    """自适应VQE算法 (ADAPT-VQE)
    
    参考文献:
        Grimsley et al., "An adaptive variational algorithm for exact molecular 
        simulations on a quantum computer", Nat. Commun. 10, 3007 (2019)
    """
    
    def __init__(self, config: VQEConfig):
        self.config = config
        self.operators: List[Any] = []
        self.operator_pool: List[Any] = []
        self.energy_history: List[float] = []
        self.parameter_history: List[np.ndarray] = []
        
    def run(self, molecule: MolecularData, hamiltonian: Any) -> VQEResult:
        """运行ADAPT-VQE算法"""
        result = VQEResult()
        
        if not QISKIT_AVAILABLE:
            raise ImportError("Qiskit required for ADAPT-VQE")
        
        # 初始化算符池
        self._build_operator_pool(molecule)
        
        # 获取初始态
        n_qubits = molecule.n_orbitals * 2 if molecule.n_orbitals else 4
        init_state = self._get_initial_state(molecule, n_qubits)
        
        current_energy = 0.0
        params = np.array([])
        
        for iteration in range(self.config.adapt_max_operators):
            # 计算梯度并选择最佳算符
            gradients = self._compute_gradients(hamiltonian, init_state)
            max_grad_idx = np.argmax(np.abs(gradients))
            max_grad = gradients[max_grad_idx]
            
            # 检查收敛
            if abs(max_grad) < self.config.adapt_threshold:
                print(f"ADAPT-VQE converged at iteration {iteration}")
                break
            
            # 添加算符到ansatz
            self.operators.append(self.operator_pool[max_grad_idx])
            params = np.append(params, 0.0)
            
            # 优化参数
            new_energy, params = self._optimize_parameters(
                hamiltonian, init_state, params
            )
            
            self.energy_history.append(new_energy)
            self.parameter_history.append(params.copy())
            
            energy_improvement = abs(current_energy - new_energy)
            current_energy = new_energy
            
            print(f"Iteration {iteration}: Energy = {current_energy:.8f}, "
                  f"Max Gradient = {max_grad:.6f}, Improvement = {energy_improvement:.8f}")
        
        result.success = True
        result.ground_state_energy = current_energy
        result.optimal_parameters = params
        result.energy_history = self.energy_history
        result.n_iterations = len(self.energy_history)
        result.n_qubits = n_qubits
        
        return result
    
    def _build_operator_pool(self, molecule: MolecularData):
        """构建激发算符池"""
        if not PYSCF_AVAILABLE:
            return
        
        mol = molecule.to_pyscf_molecule()
        n_occ = mol.nelectron // 2
        n_vir = mol.nao - n_occ
        
        # 单激发算符: a^\dagger_p a_q
        for i in range(n_occ):
            for a in range(n_vir):
                # 简化表示 - 实际应该构建费米子算符
                self.operator_pool.append(f"s_{i}_{a}")
        
        # 双激发算符: a^\dagger_p a^\dagger_q a_r a_s
        for i in range(n_occ):
            for j in range(i+1, n_occ):
                for a in range(n_vir):
                    for b in range(a+1, n_vir):
                        self.operator_pool.append(f"d_{i}_{j}_{a}_{b}")
    
    def _get_initial_state(self, molecule: MolecularData, n_qubits: int) -> Any:
        """获取Hartree-Fock初始态"""
        if QISKIT_AVAILABLE:
            from qiskit_nature.second_q.circuit.library import HartreeFock
            mapper = JordanWignerMapper()
            return HartreeFock(
                num_spatial_orbitals=n_qubits // 2,
                num_particles=(molecule.n_electrons // 2, molecule.n_electrons // 2),
                qubit_mapper=mapper
            )
        return None
    
    def _compute_gradients(self, hamiltonian: Any, init_state: Any) -> np.ndarray:
        """计算每个算符的梯度"""
        # 简化的梯度计算 - 实际需要测量对易子
        gradients = np.random.random(len(self.operator_pool)) * 0.1
        return gradients
    
    def _optimize_parameters(self, hamiltonian: Any, init_state: Any, 
                            params: np.ndarray) -> Tuple[float, np.ndarray]:
        """优化ansatz参数"""
        # 简化的优化 - 实际需要VQE优化
        from scipy.optimize import minimize
        
        def energy_fn(x):
            return np.sum(x**2) + 1.0  # 占位符
        
        result = minimize(energy_fn, params, method='COBYLA')
        return result.fun, result.x


class VQEInterface:
    """VQE主接口类"""
    
    def __init__(self, config: Optional[VQEConfig] = None):
        self.config = config or VQEConfig()
        self._setup_optimizer()
        self._setup_backend()
        
    def _setup_optimizer(self):
        """设置优化器"""
        if QISKIT_AVAILABLE:
            optimizers = {
                "COBYLA": COBYLA(maxiter=self.config.max_iterations, 
                                tol=self.config.convergence_tolerance),
                "L_BFGS_B": L_BFGS_B(maxiter=self.config.max_iterations),
                "SLSQP": SLSQP(maxiter=self.config.max_iterations)
            }
            self.optimizer = optimizers.get(self.config.optimizer, optimizers["COBYLA"])
        else:
            self.optimizer = None
    
    def _setup_backend(self):
        """设置量子后端"""
        if QISKIT_AVAILABLE:
            from qiskit import Aer
            if self.config.backend == "statevector":
                self.backend = Aer.get_backend('statevector_simulator')
            elif self.config.backend == "qasm":
                self.backend = Aer.get_backend('qasm_simulator')
            else:
                self.backend = Aer.get_backend('statevector_simulator')
        else:
            self.backend = None
    
    def compute_ground_state(self, molecule: MolecularData) -> VQEResult:
        """
        计算分子基态能量
        
        Parameters:
            molecule: 分子数据
            
        Returns:
            VQE计算结果
        """
        result = VQEResult()
        
        # 获取分子哈密顿量
        hamiltonian, n_qubits = self._get_hamiltonian(molecule)
        result.n_qubits = n_qubits
        
        # 选择ansatz
        ansatz = self._build_ansatz(molecule, n_qubits)
        result.n_cnots = ansatz.num_nonlocal_gates() if hasattr(ansatz, 'num_nonlocal_gates') else None
        result.circuit_depth = ansatz.decompose().depth() if hasattr(ansatz, 'decompose') else None
        result.ansatz_circuit = ansatz
        
        # 运行VQE
        if QISKIT_AVAILABLE and self.config.ansatz_type != AnsatzType.ADAPT:
            result = self._run_standard_vqe(hamiltonian, ansatz, result)
        elif self.config.ansatz_type == AnsatzType.ADAPT:
            adapt_vqe = ADAPTVQE(self.config)
            result = adapt_vqe.run(molecule, hamiltonian)
        else:
            result = self._run_numpy_vqe(hamiltonian, molecule, n_qubits)
        
        # 计算额外性质
        if result.success:
            self._compute_properties(result, molecule, ansatz)
        
        return result
    
    def _get_hamiltonian(self, molecule: MolecularData) -> Tuple[Any, int]:
        """获取分子哈密顿量"""
        if QISKIT_AVAILABLE:
            # 使用Qiskit Nature
            driver = PySCFDriver(
                atom=molecule.to_xyz(),
                basis=molecule.basis,
                charge=molecule.charge,
                spin=molecule.spin,
                unit=MolecularData.unit
            )
            
            problem = driver.run()
            
            # 应用变换
            mapper = self._get_mapper()
            
            if self.config.use_two_qubit_reduction and self.config.mapper_type == MapperType.PARITY:
                # 双量子比特约简
                pass
            
            hamiltonian = mapper.map(problem.hamiltonian.second_q_op())
            n_qubits = hamiltonian.num_qubits
            
            return hamiltonian, n_qubits
        
        elif PYSCF_AVAILABLE:
            # 使用PySCF计算并手动构建哈密顿量
            mol = molecule.to_pyscf_molecule()
            n_qubits = mol.nao * 2
            
            # 简化版：返回占位符
            hamiltonian = None
            return hamiltonian, n_qubits
        
        else:
            raise ImportError("Either Qiskit Nature or PySCF required")
    
    def _build_ansatz(self, molecule: MolecularData, n_qubits: int) -> Any:
        """构建ansatz电路"""
        n_electrons = molecule.n_electrons or 2
        
        if self.config.ansatz_type == AnsatzType.UCCSD:
            builder = UCCSDAnsatz(self.config)
        elif self.config.ansatz_type == AnsatzType.HEA:
            builder = HardwareEfficientAnsatz(self.config)
        else:
            builder = UCCSDAnsatz(self.config)
        
        return builder.build(n_qubits, n_electrons, None)
    
    def _run_standard_vqe(self, hamiltonian: Any, ansatz: Any, 
                          result: VQEResult) -> VQEResult:
        """运行标准VQE"""
        # 使用Qiskit算法
        estimator = Estimator()
        
        vqe = QiskitVQE(
            estimator=estimator,
            ansatz=ansatz,
            optimizer=self.optimizer
        )
        
        # 计算基态
        eigenvalue = vqe.compute_minimum_eigenvalue(hamiltonian)
        
        result.success = True
        result.ground_state_energy = eigenvalue.eigenvalue.real
        result.optimal_parameters = eigenvalue.optimal_parameters
        result.n_iterations = eigenvalue.cost_function_evals
        
        return result
    
    def _run_numpy_vqe(self, hamiltonian: Any, molecule: MolecularData, 
                       n_qubits: int) -> VQEResult:
        """使用NumPy运行简化版VQE (用于调试)"""
        result = VQEResult()
        
        if PYSCF_AVAILABLE:
            # 使用FCI作为参考
            mol = molecule.to_pyscf_molecule()
            mf = scf.RHF(mol)
            mf.kernel()
            
            cisolver = fci.FCI(mf)
            e_fci, _ = cisolver.kernel()
            
            result.success = True
            result.ground_state_energy = e_fci
            result.metadata["method"] = "FCI"
        
        return result
    
    def _compute_properties(self, result: VQEResult, molecule: MolecularData, 
                           ansatz: Any):
        """计算分子性质"""
        if not QISKIT_AVAILABLE:
            return
        
        # 这里可以添加dipole moment等性质的计算
        pass
    
    def _get_mapper(self):
        """获取费米子-量子比特映射器"""
        if not QISKIT_AVAILABLE:
            return None
        
        from qiskit_nature.second_q.mappers import (
            JordanWignerMapper, ParityMapper, BravyiKitaevMapper
        )
        
        if self.config.mapper_type == MapperType.JORDAN_WIGNER:
            return JordanWignerMapper()
        elif self.config.mapper_type == MapperType.PARITY:
            return ParityMapper()
        elif self.config.mapper_type == MapperType.BRAVYI_KITAEV:
            return BravyiKitaevMapper()
        else:
            return JordanWignerMapper()
    
    def compute_potential_energy_surface(self, molecule: MolecularData,
                                        coordinate: str,
                                        values: np.ndarray) -> Dict[str, Any]:
        """
        计算势能面
        
        Parameters:
            molecule: 基态分子几何
            coordinate: 坐标类型 ("bond_length", "angle", "dihedral")
            values: 坐标值列表
            
        Returns:
            包含能量和坐标的字典
        """
        energies = []
        results = []
        
        for val in values:
            # 修改分子几何
            mod_mol = self._modify_coordinate(molecule, coordinate, val)
            
            # 计算能量
            result = self.compute_ground_state(mod_mol)
            
            if result.success:
                energies.append(result.ground_state_energy)
                results.append(result)
            else:
                energies.append(None)
        
        return {
            "coordinates": values.tolist(),
            "energies": energies,
            "results": results,
            "coordinate_type": coordinate
        }
    
    def _modify_coordinate(self, molecule: MolecularData, 
                          coordinate: str, value: float) -> MolecularData:
        """修改分子坐标"""
        # 简化实现 - 实际应该根据coordinate类型修改原子位置
        import copy
        new_mol = copy.deepcopy(molecule)
        return new_mol


class VQEMolecularDatabase:
    """VQE分子数据库 - 存储和检索分子计算结果"""
    
    def __init__(self):
        self.molecules: Dict[str, MolecularData] = {}
        self.results: Dict[str, VQEResult] = {}
    
    def add_molecule(self, name: str, molecule: MolecularData):
        """添加分子到数据库"""
        self.molecules[name] = molecule
    
    def get_molecule(self, name: str) -> Optional[MolecularData]:
        """获取分子"""
        return self.molecules.get(name)
    
    def store_result(self, name: str, result: VQEResult):
        """存储计算结果"""
        self.results[name] = result
    
    def get_result(self, name: str) -> Optional[VQEResult]:
        """获取计算结果"""
        return self.results.get(name)
    
    def list_molecules(self) -> List[str]:
        """列出所有分子"""
        return list(self.molecules.keys())
    
    def get_energy_table(self) -> Dict[str, float]:
        """获取能量表"""
        return {
            name: result.ground_state_energy 
            for name, result in self.results.items()
            if result.success
        }


# 预定义分子库
MOLECULE_LIBRARY = {
    "H2": MolecularData(
        atoms=[("H", (0.0, 0.0, 0.0)), ("H", (0.0, 0.0, 0.74))],
        basis="sto-3g",
        charge=0,
        spin=0
    ),
    "LiH": MolecularData(
        atoms=[("Li", (0.0, 0.0, 0.0)), ("H", (0.0, 0.0, 1.6))],
        basis="sto-3g",
        charge=0,
        spin=0
    ),
    "H2O": MolecularData(
        atoms=[
            ("O", (0.0, 0.0, 0.0)),
            ("H", (0.757, 0.586, 0.0)),
            ("H", (-0.757, 0.586, 0.0))
        ],
        basis="sto-3g",
        charge=0,
        spin=0
    ),
    "NH3": MolecularData(
        atoms=[
            ("N", (0.0, 0.0, 0.0)),
            ("H", (0.94, 0.0, 0.33)),
            ("H", (-0.47, 0.81, 0.33)),
            ("H", (-0.47, -0.81, 0.33))
        ],
        basis="sto-3g",
        charge=0,
        spin=0
    )
}


def run_h2_calculation(bond_length: float = 0.74, 
                       config: Optional[VQEConfig] = None) -> VQEResult:
    """
    运行H2分子VQE计算
    
    Parameters:
        bond_length: H-H键长 (Angstrom)
        config: VQE配置
        
    Returns:
        VQE结果
    """
    molecule = MolecularData(
        atoms=[("H", (0.0, 0.0, 0.0)), ("H", (0.0, 0.0, bond_length))],
        basis="sto-3g",
        charge=0,
        spin=0
    )
    
    vqe = VQEInterface(config or VQEConfig())
    return vqe.compute_ground_state(molecule)


def run_lih_calculation(bond_length: float = 1.6,
                        config: Optional[VQEConfig] = None) -> VQEResult:
    """
    运行LiH分子VQE计算
    
    Parameters:
        bond_length: Li-H键长 (Angstrom)
        config: VQE配置
        
    Returns:
        VQE结果
    """
    molecule = MolecularData(
        atoms=[("Li", (0.0, 0.0, 0.0)), ("H", (0.0, 0.0, bond_length))],
        basis="sto-3g",
        charge=0,
        spin=0
    )
    
    vqe = VQEInterface(config or VQEConfig())
    return vqe.compute_ground_state(molecule)


if __name__ == "__main__":
    # 示例：运行H2计算
    print("Running H2 VQE calculation...")
    
    config = VQEConfig(
        ansatz_type=AnsatzType.UCCSD,
        optimizer="COBYLA",
        max_iterations=1000
    )
    
    result = run_h2_calculation(bond_length=0.74, config=config)
    
    print(f"Ground state energy: {result.ground_state_energy:.8f} Hartree")
    print(f"Number of iterations: {result.n_iterations}")
    print(f"Number of qubits: {result.n_qubits}")
