"""
智能代码生成模块 - Intelligent Code Generator
===========================================
用于从自然语言生成DFT输入、自动修复脚本错误和构建工作流。

Author: DFT-LAMMPS Team
Date: 2025
"""

import os
import re
import json
from typing import Dict, List, Optional, Any, Union, Tuple
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
import logging
import subprocess
from collections import defaultdict

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class CodeLanguage(Enum):
    """代码语言/格式枚举"""
    VASP = "vasp"
    QUANTUM_ESPRESSO = "quantum_espresso"
    LAMMPS = "lammps"
    CP2K = "cp2k"
    GAUSSIAN = "gaussian"
    ORCA = "orca"
    PYTHON = "python"
    BASH = "bash"
    SLURM = "slurm"


class CalculationType(Enum):
    """计算类型枚举"""
    SCF = "scf"
    RELAX = "relax"
    BANDS = "bands"
    DOS = "dos"
    MD = "md"
    PHONON = "phonon"
    OPTIMIZATION = "optimization"
    TS = "transition_state"
    NEB = "neb"


@dataclass
class CodeTemplate:
    """代码模板数据结构"""
    name: str
    language: CodeLanguage
    calc_type: CalculationType
    template: str
    description: str = ""
    parameters: Dict[str, Any] = field(default_factory=dict)
    required_files: List[str] = field(default_factory=list)


@dataclass
class GeneratedCode:
    """生成的代码数据结构"""
    language: CodeLanguage
    calc_type: CalculationType
    main_input: str
    auxiliary_files: Dict[str, str] = field(default_factory=dict)
    explanation: str = ""
    warnings: List[str] = field(default_factory=list)
    suggestions: List[str] = field(default_factory=list)


@dataclass
class ErrorFix:
    """错误修复建议"""
    original_error: str
    error_type: str
    suggested_fix: str
    fixed_code: str
    explanation: str
    confidence: float = 0.0


class PromptEngineer:
    """提示词工程类 - 构建高质量的代码生成提示"""
    
    # 软件特定的最佳实践
    BEST_PRACTICES = {
        CodeLanguage.VASP: {
            "general": [
                "Always check convergence with respect to ENCUT and KPOINTS",
                "Use ISPIN=2 for magnetic systems",
                "Set LORBIT=11 for projected DOS analysis",
                "Use ISMEAR=-5 for semiconductors/insulators with dense k-mesh"
            ],
            "scf": [
                "Start with ICHARG=2 for initial SCF",
                "Use ALGO=Normal or Fast for standard calculations"
            ],
            "relax": [
                "Use ISIF=3 for full relaxation (cell + ions)",
                "Set EDIFFG negative for force convergence (e.g., -0.01)"
            ],
            "bands": [
                "First run SCF calculation and save CHGCAR",
                "Set ICHARG=11 and read CHGCAR for band structure"
            ]
        },
        CodeLanguage.QUANTUM_ESPRESSO: {
            "general": [
                "Always test convergence with respect to ecutwfc and k-points",
                "Use smearing for metals, not for insulators",
                "Check total energy convergence carefully"
            ]
        },
        CodeLanguage.LAMMPS: {
            "general": [
                "Always specify neighbor list settings",
                "Use appropriate timestep based on fastest motion",
                "Dump trajectory for analysis"
            ]
        }
    }
    
    # 元素到推荐截断能的映射 (eV)
    ENCUT_RECOMMENDATIONS = {
        'H': 250, 'He': 300, 'Li': 250, 'Be': 300, 'B': 300, 'C': 400, 'N': 400,
        'O': 400, 'F': 400, 'Ne': 400, 'Na': 250, 'Mg': 250, 'Al': 250, 'Si': 250,
        'P': 300, 'S': 300, 'Cl': 300, 'Ar': 300, 'K': 250, 'Ca': 250, 'Sc': 250,
        'Ti': 250, 'V': 250, 'Cr': 250, 'Mn': 250, 'Fe': 300, 'Co': 300, 'Ni': 300,
        'Cu': 300, 'Zn': 300, 'Ga': 250, 'Ge': 250, 'As': 250, 'Se': 250, 'Br': 250,
        'Kr': 250, 'Rb': 250, 'Sr': 250, 'Y': 250, 'Zr': 250, 'Nb': 250, 'Mo': 250,
        'Tc': 250, 'Ru': 250, 'Rh': 250, 'Pd': 250, 'Ag': 250, 'Cd': 250, 'In': 250,
        'Sn': 250, 'Sb': 250, 'Te': 250, 'I': 250, 'Xe': 250, 'Cs': 250, 'Ba': 250,
        'La': 250, 'Hf': 250, 'Ta': 250, 'W': 250, 'Re': 250, 'Os': 250, 'Ir': 250,
        'Pt': 250, 'Au': 250, 'Hg': 250, 'Tl': 250, 'Pb': 250, 'Bi': 250
    }
    
    def __init__(self):
        self.templates = self._load_templates()
    
    def _load_templates(self) -> Dict[str, CodeTemplate]:
        """加载代码模板"""
        templates = {}
        
        # VASP SCF模板
        templates["vasp_scf"] = CodeTemplate(
            name="VASP SCF Calculation",
            language=CodeLanguage.VASP,
            calc_type=CalculationType.SCF,
            template="""# VASP SCF Calculation Input
# Generated by DFT-LAMMPS Code Generator

# System Settings
SYSTEM = {system_name}
ISTART = 0
ICHARG = 2

# Electronic Structure
ENCUT = {encut}
ISMEAR = {ismear}
SIGMA = {sigma}
ALGO = {algo}
EDIFF = {ediff}
NELM = {nelm}
NELMIN = {nelmin}

# Spin
ISPIN = {ispin}
MAGMOM = {magmom}

# Output Control
LWAVE = .TRUE.
LCHARG = .TRUE.
LORBIT = 11

# Parallelization
NCORE = {ncore}
KPAR = {kpar}
""",
            description="Standard VASP SCF calculation INCAR",
            parameters={
                "system_name": "Default System",
                "encut": 520,
                "ismear": 0,
                "sigma": 0.05,
                "algo": "Normal",
                "ediff": "1E-6",
                "nelm": 100,
                "nelmin": 4,
                "ispin": 1,
                "magmom": "",
                "ncore": 4,
                "kpar": 1
            }
        )
        
        # VASP Relaxation模板
        templates["vasp_relax"] = CodeTemplate(
            name="VASP Geometry Optimization",
            language=CodeLanguage.VASP,
            calc_type=CalculationType.RELAX,
            template="""# VASP Geometry Optimization Input
# Generated by DFT-LAMMPS Code Generator

# System Settings
SYSTEM = {system_name}
ISTART = 0
ICHARG = 2

# Electronic Structure
ENCUT = {encut}
ISMEAR = {ismear}
SIGMA = {sigma}
ALGO = {algo}
EDIFF = {ediff}

# Ionic Relaxation
IBRION = {ibrion}
ISIF = {isif}
NSW = {nsw}
EDIFFG = {ediffg}
POTIM = {potim}

# Spin
ISPIN = {ispin}

# Output Control
LWAVE = .FALSE.
LCHARG = .TRUE.
""",
            description="VASP geometry optimization INCAR",
            parameters={
                "system_name": "Relaxation",
                "encut": 520,
                "ismear": 0,
                "sigma": 0.05,
                "algo": "Normal",
                "ediff": "1E-6",
                "ibrion": 2,
                "isif": 3,
                "nsw": 100,
                "ediffg": "-0.01",
                "potim": 0.5,
                "ispin": 1
            }
        )
        
        # VASP Band Structure模板
        templates["vasp_bands"] = CodeTemplate(
            name="VASP Band Structure",
            language=CodeLanguage.VASP,
            calc_type=CalculationType.BANDS,
            template="""# VASP Band Structure Calculation
# Generated by DFT-LAMMPS Code Generator

# System Settings
SYSTEM = {system_name}
ISTART = 1
ICHARG = 11

# Electronic Structure
ENCUT = {encut}
ISMEAR = {ismear}
SIGMA = {sigma}
ALGO = {algo}
EDIFF = {ediff}

# Band Structure Specific
LORBIT = 11
NEDOS = 3000

# Spin
ISPIN = {ispin}

# Output Control
LWAVE = .FALSE.
LCHARG = .FALSE.
""",
            description="VASP band structure INCAR (requires pre-converged CHGCAR)",
            parameters={
                "system_name": "Band Structure",
                "encut": 520,
                "ismear": 0,
                "sigma": 0.05,
                "algo": "Normal",
                "ediff": "1E-6",
                "ispin": 1
            }
        )
        
        # LAMMPS MD模板
        templates["lammps_md"] = CodeTemplate(
            name="LAMMPS Molecular Dynamics",
            language=CodeLanguage.LAMMPS,
            calc_type=CalculationType.MD,
            template="""# LAMMPS Molecular Dynamics Input
# Generated by DFT-LAMMPS Code Generator

# Initialization
units {units}
atom_style {atom_style}
boundary p p p
read_data {data_file}

# Potential
{potential_commands}

# Neighbor list
neighbor {neighbor_skin} bin
neigh_modify every {neigh_every} delay {neigh_delay} check yes

# Thermodynamic output
thermo {thermo_freq}
thermo_style custom step temp pe ke etotal press vol density

# Minimization (optional)
# min_style cg
# minimize 1.0e-4 1.0e-6 1000 10000

# MD Settings
timestep {timestep}
fix {integrator} all npt temp {temp} {temp} {tdamp} iso {pressure} {pressure} {pdamp}

# Output
dump {dump_name} all atom {dump_freq} {dump_file}
dump_modify {dump_name} element {elements}

# Run
run {nsteps}

# Write final configuration
write_data {output_file}
""",
            description="LAMMPS NPT molecular dynamics input",
            parameters={
                "units": "metal",
                "atom_style": "atomic",
                "data_file": "structure.data",
                "potential_commands": "pair_style eam/alloy\npair_coeff * * potential.eam.alloy *",
                "neighbor_skin": 2.0,
                "neigh_every": 1,
                "neigh_delay": 0,
                "thermo_freq": 100,
                "timestep": 0.001,
                "integrator": "1",
                "temp": 300.0,
                "tdamp": 0.1,
                "pressure": 0.0,
                "pdamp": 1.0,
                "dump_name": "1",
                "dump_freq": 1000,
                "dump_file": "trajectory.dump",
                "elements": "Al Cu",
                "nsteps": 100000,
                "output_file": "final.data"
            }
        )
        
        # Quantum ESPRESSO SCF模板
        templates["qe_scf"] = CodeTemplate(
            name="Quantum ESPRESSO SCF",
            language=CodeLanguage.QUANTUM_ESPRESSO,
            calc_type=CalculationType.SCF,
            template="""&CONTROL
    calculation = 'scf'
    prefix = '{prefix}'
    outdir = '{outdir}'
    pseudo_dir = '{pseudo_dir}'
    tprnfor = .true.
    tstress = .true.
/
&SYSTEM
    ibrav = {ibrav}
    nat = {nat}
    ntyp = {ntyp}
    ecutwfc = {ecutwfc}
    ecutrho = {ecutrho}
    occupations = '{occupations}'
    smearing = '{smearing}'
    degauss = {degauss}
/
&ELECTRONS
    diagonalization = '{diagonalization}'
    mixing_mode = '{mixing_mode}'
    mixing_beta = {mixing_beta}
    conv_thr = {conv_thr}
    electron_maxstep = {electron_maxstep}
/
ATOMIC_SPECIES
{atomic_species}
ATOMIC_POSITIONS {alat}
{atomic_positions}
K_POINTS {kpoint_type}
{kpoints}
""",
            description="Quantum ESPRESSO SCF input",
            parameters={
                "prefix": "system",
                "outdir": "./tmp/",
                "pseudo_dir": "./pseudo/",
                "ibrav": 0,
                "nat": 1,
                "ntyp": 1,
                "ecutwfc": 40,
                "ecutrho": 320,
                "occupations": "smearing",
                "smearing": "gaussian",
                "degauss": 0.01,
                "diagonalization": "david",
                "mixing_mode": "plain",
                "mixing_beta": 0.7,
                "conv_thr": "1.0d-8",
                "electron_maxstep": 100,
                "atomic_species": "Al 26.9815 Al.pbe-n-kjpaw_psl.1.0.0.UPF",
                "alat": "angstrom",
                "atomic_positions": "Al 0.0 0.0 0.0",
                "kpoint_type": "automatic",
                "kpoints": "4 4 4 0 0 0"
            }
        )
        
        # Python分析脚本模板
        templates["python_analysis"] = CodeTemplate(
            name="Python Analysis Script",
            language=CodeLanguage.PYTHON,
            calc_type=CalculationType.SCF,
            template="""#!/usr/bin/env python3
\"\"\"
DFT Analysis Script
Generated by DFT-LAMMPS Code Generator
\"\"\"

import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import json

# Configuration
INPUT_FILE = "{input_file}"
OUTPUT_DIR = "{output_dir}"

{analysis_code}

if __name__ == "__main__":
    main()
""",
            description="Python script template for DFT analysis",
            parameters={
                "input_file": "vasprun.xml",
                "output_dir": "./analysis_output",
                "analysis_code": "# Add your analysis code here"
            }
        )
        
        # Slurm作业脚本模板
        templates["slurm_job"] = CodeTemplate(
            name="Slurm Job Script",
            language=CodeLanguage.SLURM,
            calc_type=CalculationType.SCF,
            template="""#!/bin/bash
#SBATCH --job-name={job_name}
#SBATCH --partition={partition}
#SBATCH --nodes={nodes}
#SBATCH --ntasks-per-node={ntasks_per_node}
#SBATCH --cpus-per-task={cpus_per_task}
#SBATCH --mem={memory}
#SBATCH --time={walltime}
#SBATCH --output={output_log}
#SBATCH --error={error_log}

# Load modules
{module_commands}

# Set environment
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export MKL_NUM_THREADS=$SLURM_CPUS_PER_TASK

# Change to working directory
cd {workdir}

# Run calculation
{run_command}

echo "Job completed at $(date)"
""",
            description="Slurm batch job script template",
            parameters={
                "job_name": "dft_calc",
                "partition": "normal",
                "nodes": 1,
                "ntasks_per_node": 16,
                "cpus_per_task": 1,
                "memory": "32G",
                "walltime": "24:00:00",
                "output_log": "%x_%j.out",
                "error_log": "%x_%j.err",
                "module_commands": "module load vasp/6.3.0",
                "workdir": "$SLURM_SUBMIT_DIR",
                "run_command": "srun vasp_std"
            }
        )
        
        return templates
    
    def build_prompt(
        self,
        description: str,
        language: CodeLanguage,
        calc_type: CalculationType,
        context: Optional[Dict[str, Any]] = None
    ) -> str:
        """
        构建代码生成提示词
        
        Args:
            description: 自然语言描述
            language: 目标语言/软件
            calc_type: 计算类型
            context: 额外上下文信息
            
        Returns:
            构建好的提示词
        """
        context = context or {}
        
        # 获取最佳实践
        best_practices = self.BEST_PRACTICES.get(language, {}).get("general", [])
        specific_practices = self.BEST_PRACTICES.get(language, {}).get(calc_type.value, [])
        all_practices = best_practices + specific_practices
        
        prompt = f"""You are an expert in computational materials science and {language.value} software.

TASK: Generate {language.value} input file(s) for a {calc_type.value} calculation.

USER REQUIREMENTS:
{description}

BEST PRACTICES TO FOLLOW:
{chr(10).join('- ' + p for p in all_practices)}

ADDITIONAL CONTEXT:
"""
        
        # 添加上下文信息
        if "material" in context:
            prompt += f"- Material: {context['material']}\n"
        if "properties" in context:
            prompt += f"- Target properties: {context['properties']}\n"
        if "hardware" in context:
            prompt += f"- Hardware constraints: {context['hardware']}\n"
        
        prompt += """
Please generate:
1. Complete, working input file(s)
2. Brief explanation of key parameters
3. Any necessary warnings or suggestions

Format your response with clear sections for each file.
"""
        
        return prompt
    
    def get_template(self, template_key: str) -> Optional[CodeTemplate]:
        """获取代码模板"""
        return self.templates.get(template_key)
    
    def estimate_encut(self, composition: Dict[str, float]) -> int:
        """
        根据化学成分估计ENCUT
        
        Args:
            composition: 元素到比例的映射
            
        Returns:
            建议的ENCUT值
        """
        max_encut = 250
        for element in composition:
            encut = self.ENCUT_RECOMMENDATIONS.get(element, 250)
            max_encut = max(max_encut, encut)
        
        # 添加一些余量
        return int(max_encut * 1.3)


class CodeGenerator:
    """
    智能代码生成器主类
    
    提供从自然语言生成DFT/MD输入文件、修复错误和构建工作流的功能。
    """
    
    def __init__(self, llm_provider: Optional[Any] = None):
        """
        初始化代码生成器
        
        Args:
            llm_provider: LLM提供商实例
        """
        self.prompt_engineer = PromptEngineer()
        self.llm = llm_provider
        self.generated_files: List[GeneratedCode] = []
        
        # 错误模式数据库
        self.error_patterns = self._load_error_patterns()
        
        logger.info("CodeGenerator initialized")
    
    def _load_error_patterns(self) -> Dict[str, List[Dict[str, str]]]:
        """加载常见错误模式"""
        return {
            CodeLanguage.VASP.value: [
                {
                    "pattern": r"VERY BAD NEWS! internal error in subroutine INVGRP",
                    "error_type": "symmetry_error",
                    "fix": "Add ISYM=0 to INCAR to disable symmetry",
                    "explanation": "VASP has trouble determining symmetry. Disabling symmetry usually fixes this."
                },
                {
                    "pattern": r"Error EDDDAV: Call to ZHEGV failed",
                    "error_type": "diagonalization_error",
                    "fix": "Try ALGO=Fast or ALGO=All. Increase NBANDS if needed.",
                    "explanation": "Diagonalization failed. Using different algorithm may help."
                },
                {
                    "pattern": r"BRMIX: very serious problems",
                    "error_type": "charge_mixing_error",
                    "fix": "Reduce BMIX or use different mixing scheme",
                    "explanation": "Charge mixing is causing instability."
                },
                {
                    "pattern": r"ZHEGV FAILED",
                    "error_type": "zhegv_error",
                    "fix": "Add LREAL=Auto or increase ENCUT",
                    "explanation": "Numerical instability in diagonalization."
                }
            ],
            CodeLanguage.LAMMPS.value: [
                {
                    "pattern": r"Neighbor list overflow",
                    "error_type": "neighbor_error",
                    "fix": "Increase neighbor skin distance or page size",
                    "explanation": "Too many neighbors per atom."
                },
                {
                    "pattern": r"Bond atoms.*missing",
                    "error_type": "bond_break",
                    "fix": "Check timestep or potential parameters. May need to reduce timestep.",
                    "explanation": "Bonds are breaking, possibly due to too large timestep."
                }
            ],
            CodeLanguage.QUANTUM_ESPRESSO.value: [
                {
                    "pattern": r"convergence NOT achieved",
                    "error_type": "scf_convergence",
                    "fix": "Increase electron_maxstep, decrease mixing_beta, or change mixing_mode",
                    "explanation": "SCF did not converge within maximum iterations."
                }
            ]
        }
    
    def generate_from_description(
        self,
        description: str,
        language: Union[str, CodeLanguage],
        calc_type: Union[str, CalculationType],
        context: Optional[Dict[str, Any]] = None,
        use_llm: bool = False
    ) -> GeneratedCode:
        """
        从自然语言描述生成代码
        
        Args:
            description: 自然语言描述
            language: 目标语言/软件
            calc_type: 计算类型
            context: 额外上下文
            use_llm: 是否使用LLM生成
            
        Returns:
            生成的代码
        """
        if isinstance(language, str):
            language = CodeLanguage(language)
        if isinstance(calc_type, str):
            calc_type = CalculationType(calc_type)
        
        context = context or {}
        
        if use_llm and self.llm:
            return self._generate_with_llm(description, language, calc_type, context)
        else:
            return self._generate_with_template(description, language, calc_type, context)
    
    def _generate_with_llm(
        self,
        description: str,
        language: CodeLanguage,
        calc_type: CalculationType,
        context: Dict[str, Any]
    ) -> GeneratedCode:
        """使用LLM生成代码"""
        prompt = self.prompt_engineer.build_prompt(
            description, language, calc_type, context
        )
        
        # 这里应该调用LLM，现在使用模板作为fallback
        response = self._mock_llm_generate(prompt)
        
        # 解析响应
        return self._parse_llm_response(response, language, calc_type)
    
    def _mock_llm_generate(self, prompt: str) -> str:
        """模拟LLM生成（用于测试）"""
        return "[MOCK LLM RESPONSE] Using template-based generation instead."
    
    def _parse_llm_response(
        self,
        response: str,
        language: CodeLanguage,
        calc_type: CalculationType
    ) -> GeneratedCode:
        """解析LLM响应"""
        # 实际实现中需要解析响应中的代码块
        # 这里简化处理
        return GeneratedCode(
            language=language,
            calc_type=calc_type,
            main_input=response,
            explanation="Generated by LLM"
        )
    
    def _generate_with_template(
        self,
        description: str,
        language: CodeLanguage,
        calc_type: CalculationType,
        context: Dict[str, Any]
    ) -> GeneratedCode:
        """使用模板生成代码"""
        
        # 查找匹配的模板
        template_key = f"{language.value}_{calc_type.value}"
        template = self.prompt_engineer.get_template(template_key)
        
        if not template:
            # 使用通用模板
            template = self._create_generic_template(language, calc_type)
        
        # 提取参数
        params = self._extract_parameters_from_description(description, context)
        
        # 合并模板默认参数和用户参数
        final_params = {**template.parameters, **params}
        
        # 渲染模板
        main_input = template.template.format(**final_params)
        
        # 生成辅助文件
        auxiliary_files = self._generate_auxiliary_files(
            language, calc_type, final_params, context
        )
        
        # 生成建议
        suggestions = self._generate_suggestions(language, calc_type, final_params)
        
        generated = GeneratedCode(
            language=language,
            calc_type=calc_type,
            main_input=main_input,
            auxiliary_files=auxiliary_files,
            explanation=f"Generated using {template.name} template",
            warnings=self._check_for_warnings(final_params),
            suggestions=suggestions
        )
        
        self.generated_files.append(generated)
        
        return generated
    
    def _create_generic_template(
        self,
        language: CodeLanguage,
        calc_type: CalculationType
    ) -> CodeTemplate:
        """创建通用模板"""
        return CodeTemplate(
            name=f"Generic {language.value} {calc_type.value}",
            language=language,
            calc_type=calc_type,
            template="# Generic template\n# Please specify parameters",
            parameters={}
        )
    
    def _extract_parameters_from_description(
        self,
        description: str,
        context: Dict[str, Any]
    ) -> Dict[str, Any]:
        """从描述中提取参数"""
        params = {}
        desc_lower = description.lower()
        
        # 提取ENCUT
        encut_match = re.search(r'encut[=\s]+(\d+)', description, re.IGNORECASE)
        if encut_match:
            params["encut"] = int(encut_match.group(1))
        
        # 提取温度
        temp_match = re.search(r'(\d+)\s*[Kk]', description)
        if temp_match:
            params["temp"] = float(temp_match.group(1))
        
        # 提取材料名称
        material_match = re.search(r'(?:for|of)\s+([A-Z][a-z]?\d*[A-Z]?\d*)', description)
        if material_match:
            params["system_name"] = material_match.group(1)
            params["material"] = material_match.group(1)
        
        # 提取k点
        kpoint_match = re.search(r'(\d+)\s*x\s*(\d+)\s*x\s*(\d+)', description)
        if kpoint_match:
            params["kpoints"] = f"{kpoint_match.group(1)} {kpoint_match.group(2)} {kpoint_match.group(3)}"
        
        # 合并上下文参数
        params.update(context)
        
        return params
    
    def _generate_auxiliary_files(
        self,
        language: CodeLanguage,
        calc_type: CalculationType,
        params: Dict[str, Any],
        context: Dict[str, Any]
    ) -> Dict[str, str]:
        """生成辅助文件"""
        aux_files = {}
        
        if language == CodeLanguage.VASP:
            # 生成KPOINTS
            if "kpoints" in params:
                aux_files["KPOINTS"] = self._generate_vasp_kpoints(params)
            
            # 生成POTCAR信息
            if "elements" in params or "material" in params:
                aux_files["POTCAR_note.txt"] = self._generate_potcar_note(params)
        
        elif language == CodeLanguage.LAMMPS:
            # 生成data文件说明
            aux_files["structure_info.txt"] = self._generate_lammps_structure_info(params)
        
        elif language == CodeLanguage.QUANTUM_ESPRESSO:
            # 生成假势说明
            aux_files["pseudopotential_note.txt"] = self._generate_qe_pseudo_note(params)
        
        return aux_files
    
    def _generate_vasp_kpoints(self, params: Dict[str, Any]) -> str:
        """生成VASP KPOINTS文件"""
        kpoints = params.get("kpoints", "4 4 4")
        
        return f"""Automatic mesh
0
Monkhorst-Pack
{kpoints}
0 0 0
"""
    
    def _generate_potcar_note(self, params: Dict[str, Any]) -> str:
        """生成POTCAR说明"""
        material = params.get("material", "Unknown")
        
        return f"""# POTCAR Setup Note for {material}

# Extract elements from formula and get corresponding POTCARs
# Example:
# For SiO2: cat $POTCAR_PATH/Si/POTCAR $POTCAR_PATH/O/POTCAR > POTCAR

# Recommended POTCAR types:
# - Standard: PBE (GGA)
# - For accurate lattice parameters: PBEsol
# - For accurate band gaps: HSE06 (requires VASP.5.4+)

# Elements in material: {material}

# Command to generate POTCAR:
# python -c "from pymatgen.io.vasp import Potcar; Potcar([{material}]).write_file('POTCAR')"
"""
    
    def _generate_lammps_structure_info(self, params: Dict[str, Any]) -> str:
        """生成LAMMPS结构文件说明"""
        return """# LAMMPS Data File Information

# Required structure.data format:
# 
# [Header]
# # Comment line
# N atoms
# M atom types
#
# xlo xhi
# ylo yhi
# zlo zhi
#
# Masses
#
# 1 mass_element_1
# 2 mass_element_2
#
# Atoms
#
# id type x y z

# You can generate this from:
# - VASP POSCAR using ovito or ASE
# - Quantum ESPRESSO output using xcrysden
# - Materials Project CIF using pymatgen

# Example ASE command:
# from ase.io import read, write
# atoms = read('POSCAR')
# write('structure.data', atoms, format='lammps-data')
"""
    
    def _generate_qe_pseudo_note(self, params: Dict[str, Any]) -> str:
        """生成Quantum ESPRESSO假势说明"""
        return """# Quantum ESPRESSO Pseudopotentials

# Download from: https://www.quantum-espresso.org/pseudopotentials/

# Recommended libraries:
# - SSSP (Standard Solid State Pseudopotentials): https://www.materialscloud.org/discover/sssp
# - PSlibrary: https://dalcorso.github.io/pslibrary/

# For high-throughput calculations, use SSSP efficiency or precision

# Place pseudopotentials in the directory specified in the input file
"""
    
    def _generate_suggestions(
        self,
        language: CodeLanguage,
        calc_type: CalculationType,
        params: Dict[str, Any]
    ) -> List[str]:
        """生成建议"""
        suggestions = []
        
        if language == CodeLanguage.VASP:
            if params.get("encut", 0) < 400:
                suggestions.append("Consider increasing ENCUT for better accuracy")
            
            if calc_type == CalculationType.BANDS:
                suggestions.append("Ensure CHGCAR from SCF calculation is present")
        
        elif language == CodeLanguage.LAMMPS:
            if "temp" in params:
                temp = params["temp"]
                if temp > 1000:
                    suggestions.append(f"High temperature ({temp}K): consider using a smaller timestep")
        
        return suggestions
    
    def _check_for_warnings(self, params: Dict[str, Any]) -> List[str]:
        """检查潜在问题"""
        warnings = []
        
        if "encut" in params and params["encut"] > 800:
            warnings.append(f"High ENCUT ({params['encut']}) may be computationally expensive")
        
        if "nsw" in params and params["nsw"] > 500:
            warnings.append("Large number of ionic steps - consider improving initial geometry")
        
        return warnings
    
    def diagnose_error(
        self,
        error_log: str,
        language: Union[str, CodeLanguage],
        current_input: str
    ) -> List[ErrorFix]:
        """
        诊断并修复错误
        
        Args:
            error_log: 错误日志内容
            language: 使用的软件
            current_input: 当前输入文件内容
            
        Returns:
            修复建议列表
        """
        if isinstance(language, str):
            language = CodeLanguage(language)
        
        fixes = []
        
        # 匹配错误模式
        patterns = self.error_patterns.get(language.value, [])
        
        for pattern_info in patterns:
            if re.search(pattern_info["pattern"], error_log):
                # 生成修复后的代码
                fixed_code = self._apply_fix(
                    current_input, pattern_info["fix"], language
                )
                
                fix = ErrorFix(
                    original_error=error_log[:200],
                    error_type=pattern_info["error_type"],
                    suggested_fix=pattern_info["fix"],
                    fixed_code=fixed_code,
                    explanation=pattern_info["explanation"],
                    confidence=0.8
                )
                fixes.append(fix)
        
        if not fixes:
            # 未匹配到已知模式，提供通用建议
            fixes.append(ErrorFix(
                original_error=error_log[:200],
                error_type="unknown",
                suggested_fix="Please check the error log carefully",
                fixed_code=current_input,
                explanation="Unknown error pattern. Check documentation.",
                confidence=0.3
            ))
        
        return fixes
    
    def _apply_fix(
        self,
        current_input: str,
        fix_instruction: str,
        language: CodeLanguage
    ) -> str:
        """应用修复"""
        fixed = current_input
        
        if language == CodeLanguage.VASP:
            # 处理INCAR修复
            if "ISYM=0" in fix_instruction and "ISYM" not in current_input:
                fixed = current_input.rstrip() + "\nISYM = 0\n"
            elif "ALGO=" in fix_instruction:
                # 替换ALGO参数
                if "ALGO" in current_input:
                    fixed = re.sub(r'ALGO\s*=\s*\w+', 'ALGO = Fast', current_input)
                else:
                    fixed = current_input.rstrip() + "\nALGO = Fast\n"
        
        elif language == CodeLanguage.LAMMPS:
            if "neighbor" in fix_instruction:
                # 增加neighbor skin
                if "neighbor" in current_input:
                    fixed = re.sub(r'neighbor\s+[\d.]+', 'neighbor 3.0', current_input)
        
        return fixed
    
    def build_workflow(
        self,
        workflow_type: str,
        stages: List[Dict[str, Any]],
        dependencies: Optional[Dict[int, List[int]]] = None
    ) -> Dict[str, Any]:
        """
        构建计算工作流
        
        Args:
            workflow_type: 工作流类型（如"band_structure", "md_equilibration"）
            stages: 各阶段配置
            dependencies: 阶段依赖关系
            
        Returns:
            工作流定义
        """
        workflow = {
            "name": workflow_type,
            "stages": [],
            "dependencies": dependencies or {},
            "scripts": {}
        }
        
        for i, stage in enumerate(stages):
            stage_def = {
                "id": i,
                "name": stage.get("name", f"stage_{i}"),
                "language": stage.get("language", "vasp"),
                "calc_type": stage.get("calc_type", "scf"),
                "description": stage.get("description", ""),
                "inputs": stage.get("inputs", {}),
                "outputs": stage.get("outputs", [])
            }
            
            # 生成该阶段的输入文件
            generated = self.generate_from_description(
                description=stage.get("description", ""),
                language=stage_def["language"],
                calc_type=stage_def["calc_type"],
                context=stage.get("context", {})
            )
            
            stage_def["generated_files"] = {
                "main": generated.main_input,
                "auxiliary": generated.auxiliary_files
            }
            
            workflow["stages"].append(stage_def)
        
        # 生成工作流脚本
        workflow["scripts"] = self._generate_workflow_scripts(workflow)
        
        return workflow
    
    def _generate_workflow_scripts(self, workflow: Dict[str, Any]) -> Dict[str, str]:
        """生成工作流执行脚本"""
        scripts = {}
        
        # 生成bash执行脚本
        bash_script = "#!/bin/bash\n# Workflow: {}\n\n".format(workflow["name"])
        
        for stage in workflow["stages"]:
            stage_id = stage["id"]
            stage_name = stage["name"]
            
            bash_script += f"# Stage {stage_id}: {stage_name}\n"
            bash_script += f"echo 'Running stage {stage_id}: {stage_name}'\n"
            
            # 检查依赖
            deps = workflow["dependencies"].get(stage_id, [])
            if deps:
                bash_script += f"# Depends on stages: {deps}\n"
                for dep in deps:
                    bash_script += f"wait_stage_{dep}\n"
            
            # 执行命令
            if stage["language"] == "vasp":
                bash_script += "cd stage_{} && mpirun vasp_std > vasp.out 2>&1\n".format(stage_id)
            elif stage["language"] == "lammps":
                bash_script += "cd stage_{} && mpirun lmp -in input.lammps > lammps.out 2>&1\n".format(stage_id)
            
            bash_script += f"echo 'Stage {stage_id} completed'\n\n"
        
        bash_script += "echo 'Workflow completed!'\n"
        
        scripts["run_workflow.sh"] = bash_script
        
        # 生成Python工作流脚本
        python_script = self._generate_python_workflow(workflow)
        scripts["run_workflow.py"] = python_script
        
        return scripts
    
    def _generate_python_workflow(self, workflow: Dict[str, Any]) -> str:
        """生成Python工作流脚本"""
        stages = workflow["stages"]
        
        script = '''#!/usr/bin/env python3
"""
Automated Workflow: {name}
Generated by DFT-LAMMPS Code Generator
"""

import subprocess
import os
import json
from pathlib import Path
from concurrent.futures import ProcessPoolExecutor
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

WORKFLOW_CONFIG = {config}

def run_stage(stage_id, stage_config):
    """Execute a workflow stage"""
    logger.info(f"Starting stage {{stage_id}}: {{stage_config['name']}}")
    
    # Change to stage directory
    stage_dir = Path(f"stage_{{stage_id}}")
    stage_dir.mkdir(exist_ok=True)
    
    # Write input files
    files = stage_config['generated_files']
    main_file = 'INCAR' if stage_config['language'] == 'vasp' else 'input.lammps'
    
    with open(stage_dir / main_file, 'w') as f:
        f.write(files['main'])
    
    for fname, content in files['auxiliary'].items():
        with open(stage_dir / fname, 'w') as f:
            f.write(content)
    
    # Run calculation
    os.chdir(stage_dir)
    
    if stage_config['language'] == 'vasp':
        cmd = ['mpirun', 'vasp_std']
    elif stage_config['language'] == 'lammps':
        cmd = ['mpirun', 'lmp', '-in', 'input.lammps']
    else:
        cmd = ['echo', 'Unknown language']
    
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=3600)
        os.chdir('..')
        
        if result.returncode == 0:
            logger.info(f"Stage {{stage_id}} completed successfully")
            return {{'stage': stage_id, 'status': 'success'}}
        else:
            logger.error(f"Stage {{stage_id}} failed: {{result.stderr}}")
            return {{'stage': stage_id, 'status': 'failed', 'error': result.stderr}}
    except subprocess.TimeoutExpired:
        logger.error(f"Stage {{stage_id}} timed out")
        os.chdir('..')
        return {{'stage': stage_id, 'status': 'timeout'}}

def main():
    """Main workflow execution"""
    results = []
    
    # Execute stages sequentially (respecting dependencies)
    for stage in WORKFLOW_CONFIG['stages']:
        result = run_stage(stage['id'], stage)
        results.append(result)
        
        if result['status'] != 'success':
            logger.error("Workflow failed. Stopping.")
            break
    
    # Save results
    with open('workflow_results.json', 'w') as f:
        json.dump(results, f, indent=2)
    
    logger.info("Workflow execution completed")

if __name__ == '__main__':
    main()
'''.format(
            name=workflow["name"],
            config=json.dumps(workflow, indent=4)
        )
        
        return script
    
    def save_generated_files(
        self,
        generated: GeneratedCode,
        output_dir: str,
        prefix: str = ""
    ):
        """
        保存生成的文件
        
        Args:
            generated: 生成的代码对象
            output_dir: 输出目录
            prefix: 文件名前缀
        """
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)
        
        # 确定主文件名
        main_filename = {
            CodeLanguage.VASP: "INCAR",
            CodeLanguage.LAMMPS: "input.lammps",
            CodeLanguage.QUANTUM_ESPRESSO: "pw.in",
            CodeLanguage.CP2K: "input.inp",
            CodeLanguage.PYTHON: "script.py",
            CodeLanguage.BASH: "run.sh",
            CodeLanguage.SLURM: "job.sh"
        }.get(generated.language, "input.txt")
        
        # 保存主输入文件
        with open(output_path / f"{prefix}{main_filename}", 'w') as f:
            f.write(generated.main_input)
        
        # 保存辅助文件
        for fname, content in generated.auxiliary_files.items():
            with open(output_path / f"{prefix}{fname}", 'w') as f:
                f.write(content)
        
        # 保存说明文件
        readme = f"""# Generated Input Files

Language: {generated.language.value}
Calculation Type: {generated.calc_type.value}

## Explanation
{generated.explanation}

## Warnings
{chr(10).join('- ' + w for w in generated.warnings) if generated.warnings else 'None'}

## Suggestions
{chr(10).join('- ' + s for s in generated.suggestions) if generated.suggestions else 'None'}
"""
        
        with open(output_path / f"{prefix}README.md", 'w') as f:
            f.write(readme)
        
        logger.info(f"Files saved to {output_dir}")


# 便捷函数
def quick_generate(
    description: str,
    language: str = "vasp",
    calc_type: str = "scf",
    **context
) -> GeneratedCode:
    """快速生成代码"""
    generator = CodeGenerator()
    return generator.generate_from_description(
        description=description,
        language=CodeLanguage(language),
        calc_type=CalculationType(calc_type),
        context=context
    )


def quick_fix(
    error_log: str,
    current_input: str,
    language: str = "vasp"
) -> List[ErrorFix]:
    """快速修复错误"""
    generator = CodeGenerator()
    return generator.diagnose_error(error_log, language, current_input)


if __name__ == "__main__":
    # 测试代码
    print("=" * 60)
    print("CodeGenerator Test")
    print("=" * 60)
    
    generator = CodeGenerator()
    
    # 测试1: VASP SCF生成
    print("\n1. Testing VASP SCF generation...")
    vasp_scf = generator.generate_from_description(
        description="Generate SCF input for SiO2 with high accuracy, 6x6x6 kpoints",
        language=CodeLanguage.VASP,
        calc_type=CalculationType.SCF
    )
    print(f"Generated {vasp_scf.language.value} input")
    print(f"Warnings: {len(vasp_scf.warnings)}")
    
    # 测试2: LAMMPS MD生成
    print("\n2. Testing LAMMPS MD generation...")
    lammps_md = generator.generate_from_description(
        description="NPT MD for Cu at 500K, 1 atm pressure, 100k steps",
        language=CodeLanguage.LAMMPS,
        calc_type=CalculationType.MD
    )
    print(f"Generated {lammps_md.language.value} input")
    print(f"Auxiliary files: {list(lammps_md.auxiliary_files.keys())}")
    
    # 测试3: 错误诊断
    print("\n3. Testing error diagnosis...")
    error_log = "Error EDDDAV: Call to ZHEGV failed"
    fixes = generator.diagnose_error(error_log, CodeLanguage.VASP, "")
    print(f"Found {len(fixes)} fixes")
    for fix in fixes:
        print(f"  - {fix.error_type}: {fix.suggested_fix}")
    
    # 测试4: 工作流构建
    print("\n4. Testing workflow building...")
    workflow = generator.build_workflow(
        workflow_type="band_structure",
        stages=[
            {
                "name": "scf",
                "description": "Self-consistent calculation for Si",
                "language": "vasp",
                "calc_type": "scf"
            },
            {
                "name": "bands",
                "description": "Band structure calculation",
                "language": "vasp",
                "calc_type": "bands"
            }
        ],
        dependencies={1: [0]}
    )
    print(f"Created workflow with {len(workflow['stages'])} stages")
    
    print("\n" + "=" * 60)
    print("All tests completed!")
    print("=" * 60)
